### ISSUE TITLE
Add missing DELETEAsync method for testing

### ISSUE THREAD

**Issue by nghiepvo** [dj-nitehawk/FastEndpoints#100]
https://github.com/dj-nitehawk/FastEndpoints/blob/1848f715e529ad877e4af4a097c65a847096443e/Src/Library/Extensions/HttpClientExtensions.cs#L10

**Comment by dj-nitehawk** [comment]
yes looks like i missed it. will be added eventually...
if someone has free time, please submit a PR 🙏

**Comment by nghiepvo** [comment]
I also was added PATCHAsync method, could you review it?

**Comment by dj-nitehawk** [comment]
will merge soon
