### ISSUE TITLE
How to calculate request time using processor

### ISSUE THREAD

**Issue by tuannguyenssu** [dj-nitehawk/FastEndpoints#114]
Dear,
How can I logging the long running request using processor?
In MediatR, I can use like this

```csharp
public class PerformanceBehavior<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse> where TRequest : IRequest<TResponse>
{
    private readonly Stopwatch _timer;
    private readonly ILogger<TRequest> _logger;

    public PerformanceBehavior (ILogger<TRequest> logger)
    {
        _timer = new Stopwatch();

        _logger = logger;
    }

    public async Task<TResponse> Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate<TResponse> next)
    {
        _timer.Start();

        var response = await next();

        _timer.Stop();

        var elapsedMilliseconds = _timer.ElapsedMilliseconds;

        if (elapsedMilliseconds > 60000)
        {
            var requestName = typeof(TRequest).Name;

            _logger.LogWarning("Long Running Request: {Name} ({ElapsedMilliseconds} milliseconds) {@Request}",
                requestName, elapsedMilliseconds, request);
        }

        return response;
    }
}
```

Thanks so much

**Comment by dj-nitehawk** [comment]
if this is applicable to all endpoints, i'd simply write it as an asp.net pipeline middleware.
if it's only applicable to a few different endpoints, then it can be achieved like so:
```csharp
public static class PerformanceCheck<TRequest>
{
    public static Pre Start => new();
    public static Post End => new();

    public class Pre : IPreProcessor<TRequest>
    {
        public Task PreProcessAsync(TRequest req, HttpContext ctx, List<ValidationFailure> failures, CancellationToken ct)
        {
            ctx.Items.Add("StartTime", DateTime.Now.Ticks);
            return Task.CompletedTask;
        }
    }

    public class Post : IPostProcessor<TRequest, object>
    {
        public Task PostProcessAsync(TRequest req, object res, HttpContext ctx, IReadOnlyCollection<ValidationFailure> failures, CancellationToken ct)
        {
            var logger = ctx.RequestServices.GetRequiredService<ILogger<TRequest>>();
            var elapsedMs = TimeSpan.FromTicks(DateTime.Now.Ticks - (long)ctx.Items["StartTime"]!).TotalMilliseconds;

            if (elapsedMs > 500)
            {
                var requestName = typeof(TRequest).Name;
                logger.LogWarning("Long Running Request: {Name} ({ElapsedMilliseconds} milliseconds) {@Request}",
                    requestName, elapsedMs, req);
            }

            return Task.CompletedTask;
        }
    }
}

public class MyRequest
{
    public string Name { get; set; }
}

public class MyEndpoint : Endpoint<MyRequest>
{
    public override void Configure()
    {
        Get("test");
        AllowAnonymous();
        PreProcessors(PerformanceCheck<MyRequest>.Start);
        PostProcessors(PerformanceCheck<MyRequest>.End);
    }

    public override async Task HandleAsync(MyRequest req, CancellationToken ct)
    {
        await Task.Delay(500);
        await SendAsync(req);
    }
}
```

**Comment by tuannguyenssu** [comment]
> if this is applicable to all endpoints, i'd simply write it as an asp.net pipeline middleware. if it's only applicable to a few different endpoints, then it can be achieved like so:
> 
> ```cs
> public static class PerformanceCheck<TRequest>
> {
>     public static Pre Start => new();
>     public static Post End => new();
> 
>     public class Pre : IPreProcessor<TRequest>
>     {
>         public Task PreProcessAsync(TRequest req, HttpContext ctx, List<ValidationFailure> failures, CancellationToken ct)
>         {
>             ctx.Items.Add("StartTime", DateTime.Now.Ticks);
>             return Task.CompletedTask;
>         }
>     }
> 
>     public class Post : IPostProcessor<TRequest, object>
>     {
>         public Task PostProcessAsync(TRequest req, object res, HttpContext ctx, IReadOnlyCollection<ValidationFailure> failures, CancellationToken ct)
>         {
>             var elapsedMs = TimeSpan.FromTicks(DateTime.Now.Ticks - (long)ctx.Items["StartTime"]!).TotalMilliseconds;
>             var logger = ctx.RequestServices.GetRequiredService<ILogger<TRequest>>();
> 
>             if (elapsedMs > 500)
>             {
>                 var requestName = typeof(TRequest).Name;
>                 logger.LogWarning("Long Running Request: {Name} ({ElapsedMilliseconds} milliseconds) {@Request}",
>                     requestName, elapsedMs, req);
>             }
> 
>             return Task.CompletedTask;
>         }
>     }
> }
> 
> public class MyRequest
> {
>     public string Name { get; set; }
> }
> 
> public class MyEndpoint : Endpoint<MyRequest>
> {
>     public override void Configure()
>     {
>         Get("test");
>         AllowAnonymous();
>         PreProcessors(PerformanceCheck<MyRequest>.Start);
>         PostProcessors(PerformanceCheck<MyRequest>.End);
>     }
> 
>     public override async Task HandleAsync(MyRequest req, CancellationToken ct)
>     {
>         await Task.Delay(500);
>         await SendAsync(req);
>     }
> }
> ```

**Comment by tuannguyenssu** [comment]
Thanks you so much :)
