### ISSUE TITLE
using source generators to cut down on endpoint/type discovery time during startup

### ISSUE THREAD

**Issue by dj-nitehawk** [dj-nitehawk/FastEndpoints#117]
currently fastendpoints uses assembly scanning to discover endpoints/validators/event handlers/summaries during startup.
https://github.com/dj-nitehawk/FastEndpoints/blob/1745ec0254da63d22bfea6d96067d047f0b8943e/Src/Library/Extensions/EndpointData.cs#L54-L70
this obviously takes some milliseconds whenever the app is run, which would not be ideal for serverless/cold start scenarios.

if we can use a source generator to produce a static class with a `System.Type[]` static property at compile time, we may be able to get rid of the type discovery time.

the end result of the source generation should be something like this:
```csharp
namespace FastEndpoints
{
    public static class DiscoveredTypes
    {
        public static readonly System.Type[] AllTypes = new System.Type[]
        {
            typeof(UsersNameSpace.MyEndpoint1),
            typeof(UsersNameSpace.MyEndpoint2),
            typeof (UsersNameSpace.MyEndpoint3)
        };
    }
}
```
if you have experience with source generators, please see if you can implement this.
this will be much appreciated by the folk who uses fastendpoints in serveless environments.

i myself got as far as trying to figure out if a `ClassDeclarationSyntax` implements a given interface such as `IEndpoint` and failed since it seems like it's not possible to get a list of interfaces a class implements inside the `SyntaxReceiver`.

**Comment by nefarius** [comment]
Started working on this in [a new branch](https://github.com/nefarius/FastEndpoints/tree/nefarius/feature/source-generators).

**Comment by nefarius** [comment]
Looks promising 😄 

![image](https://user-images.githubusercontent.com/286631/169362017-fa5062eb-03eb-4f00-8e37-2bd3b2080ca5.png)

**Comment by dj-nitehawk** [comment]
@nefarius forgot to tell you... i had to change the assembly discovery logic in order to cater for #121
pls pull those changes into your fork/branch.

**Comment by nefarius** [comment]
@dj-nitehawk so you need a property returning a list of assemblies instead of types, did I get that right?

**Comment by dj-nitehawk** [comment]
nevermind... looks like you've already pulled the latest code:
https://github.com/nefarius/FastEndpoints/blob/nefarius/feature/source-generators/Src/Library/Extensions/EndpointData.cs

carry on... 😁

**Comment by nefarius** [comment]
From my point of view it's done. How to proceed from here, some individuals test it or PR and make pre-release NuGets or...?

**Comment by dj-nitehawk** [comment]
yeah send in a PR. I'll do some testing myself and release a beta.

**Comment by dj-nitehawk** [comment]
@nefarius 
soooo... 
i made a few minor tweaks and pushed out `v4.3.0-beta1` to nuget.
however, it's not finding the types at all.
i tried with the [Web](https://github.com/dj-nitehawk/FastEndpoints/blob/main/Web/Web.csproj#L24) project as well as the following test project: [GeneratorTest.zip](https://github.com/dj-nitehawk/FastEndpoints/files/8743467/GeneratorTest.zip)
the g.cs file is created but the `AllTypes` field is always empty.

weid thing is, if i add a package reference to benchmarkdotnet to the test project
```csharp
<PackageReference Include="BenchmarkDotNet" Version="0.13.1" />
```
it generates the following:
```csharp
using System;
namespace FastEndpoints
{
    public static class DiscoveredTypes
    {
        public static readonly System.Type[] AllTypes = new System.Type[]
        {
            typeof(BenchmarkDotNet.Toolchains.InProcess.InProcessValidator),
            typeof(BenchmarkDotNet.Validators.BaselineValidator),
            typeof(BenchmarkDotNet.Validators.CompilationValidator),
            typeof(BenchmarkDotNet.Validators.ConfigCompatibilityValidator),
            typeof(BenchmarkDotNet.Validators.ConfigValidator),
            typeof(BenchmarkDotNet.Validators.DeferredExecutionValidator),
            typeof(BenchmarkDotNet.Validators.DiagnosersValidator),
            typeof(BenchmarkDotNet.Validators.ExecutionValidator),
            typeof(BenchmarkDotNet.Validators.GenericBenchmarksValidator),
            typeof(BenchmarkDotNet.Validators.JitOptimizationsValidator),
            typeof(BenchmarkDotNet.Validators.ParamsAllValuesValidator),
            typeof(BenchmarkDotNet.Validators.ReturnValueValidator),
            typeof(BenchmarkDotNet.Validators.RunModeValidator),
            typeof(BenchmarkDotNet.Validators.SetupCleanupValidator),
            typeof(BenchmarkDotNet.Validators.ShadowCopyValidator),
        };
    }
}
```

**Comment by nefarius** [comment]
Will check when back!

**Comment by dj-nitehawk** [comment]
it works with the test project above but...
does not work with the [Web](https://github.com/dj-nitehawk/FastEndpoints/tree/main/Web) project for example.
the `AllTypes` property is still empty.
not sure if it's because of multi project solutions or just deeply nested endpoints/ namespaces like:
https://github.com/dj-nitehawk/FastEndpoints/blob/1d88daba3d9845e3882e20cd1cc2c907b7c9d1dd/Web/%5BFeatures%5D/Inventory/Manage/Create/Endpoint.cs#L1
will you be able to have a looksie?

**Comment by nefarius** [comment]
![](https://c.tenor.com/DuitE86zupUAAAAC/of-course-obviously.gif)

**Comment by nefarius** [comment]
Yep, the nested namespace lookup was still faulty, got it fixed and debugged through and boom! Look at that:

![image](https://user-images.githubusercontent.com/286631/169875778-ebb5cdf3-d677-4fa2-9333-db2e11d07142.png)

**Comment by dj-nitehawk** [comment]
bloody marvelous...
hey i was thinking, you know how it just silently switches over to reflection if source generation didn't work.
should we make it so that app won't start and throw an exception in case source generation doesn't work.
because the user has explicitly asked for sourcegen by referencing the nuget package.
if it doesn't work, we need to let them know that it's not working for that environment.
or at least write a log warning or something?
what do you think?

**Comment by nefarius** [comment]
I am in favour of just bluntly throwing an exception; if it doesn't work it should be pointed out and addressed instead of silently swallowed.

**Comment by dj-nitehawk** [comment]
great! will you pls throw that in there as well?
cheers!
i'm off to bed. will check and merge tomorrow.
well done btw mate...
i would've struggled for weeks with these damn source generators ;-)

**Comment by nefarius** [comment]
Can do! Have a good one! Sure was my pleasure 😁

**Comment by dj-nitehawk** [comment]
@nefarius 
third pr definitely was the charm ;-)
btw i [simplified](https://github.com/dj-nitehawk/FastEndpoints/commit/2f962939d36d67eb43c2eee01753aa39385029bd) the `EndpointData.cs` a bit.
user will have to do this now:
```csharp
builder.Services.AddFastEndpoints(new() { SourceGeneratorDiscoveredTypes = DiscoveredTypes.All });
```
pushed `v4.3.0-beta4` to nuget for final testing.
will close this issue now since feature looks to be stable.

**Comment by snc-software** [comment]
Hey so i've been following this and i'm getting the following error.

Program.cs(15, 76): [CS0103] The name 'DiscoveredTypes' does not exist in the current context


Here is the code snippet i am using to register the files.

```
var builder = WebApplication.CreateBuilder(args);
var config = builder.Configuration;

builder.Services.AddFastEndpoints(new() { SourceGeneratorDiscoveredTypes = DiscoveredTypes.All });
```

i can look at the discovered types and it's populating correctly, i just can't seem to figure out how to add the generated file to my project so it can used.

Any help would be appreciated.

**Comment by dj-nitehawk** [comment]
@snc-software can you try the following test project: [GeneratorTest.zip](https://github.com/dj-nitehawk/FastEndpoints/files/8767964/GeneratorTest.zip)

**Comment by snc-software** [comment]
@dj-nitehawk Hi. Thanks for providing that for me. 
 As you can see below VS22 (Professional if that matters i doubt but still) doesn't even find the file and treats it as unknown

![image](https://user-images.githubusercontent.com/39570463/170202279-e7261b77-485a-4e0b-9064-d5880d6f13e9.png)

As you can see here in Rider 2021.3.3 (my preferred IDE) we find the file and it is stored in rider's generated files, but you can see it is still not compiled.
![image](https://user-images.githubusercontent.com/39570463/170203214-d1212c4c-0d6a-4141-ab84-db65de065e78.png)

**Comment by dj-nitehawk** [comment]
@nefarius any idea what's happening here?
i am totally baffled...

@snc-software can you take a screenshot of fully exanded `dependancies > analyzers > fastendpoints.generator` node?

**Comment by snc-software** [comment]
@dj-nitehawk Yes of course. 

This is as expanded as it goes i'm afraid 

![image](https://user-images.githubusercontent.com/39570463/170204745-43a8cdb2-88a3-4f3e-a663-4a0fca5fe472.png)

**Comment by dj-nitehawk** [comment]
looks like source generation is not working in your environment for some reason.
maybe try installing the .net compiler platform sdk (if not already installed).
other than that, i'm out of ideas :-(

![screen-record-1653463768](https://user-images.githubusercontent.com/7043768/170205838-2ec3ce8f-72ec-42e9-a4a9-2cf3663f7b42.png)

**Comment by snc-software** [comment]
@dj-nitehawk that seems to have solved it ha ha  

thanks so much for the assist. 

![image](https://user-images.githubusercontent.com/39570463/170208900-36199ee0-603e-4758-a130-8cef89f8e25f.png)

**Comment by nefarius** [comment]
Great! Yeah, unfortunately when some dependency is missing it just silently fails instead of giving meaningful error messages, I lost a bunch of hair over that too 😅

**Comment by jorge-ribeiro-evaltec** [comment]
Just to let people know, using the source generator wasn't working here - I was getting an error that the symbol was not found. To make everything work, I had to install the newest .NET 6 SDK (version 6.0.300 as of now) - compilation did not work with older versions.

**Comment by nefarius** [comment]
> I had to install the newest .NET 6 SDK (version 6.0.300 as of now)

That's a "known" issue with the latest version of `Microsoft.CodeAnalysis.CSharp` which the source generator depends on.

**Comment by eshmanev** [comment]
I have recently faced the same problem on VS 17.8.5. Installed .NET Compiler Platform SDK and .NET 8 SDK, but it stills does not work. I have also tried to build the Web project from the FastEndpoints sources, but it has the same error.

**Comment by dj-nitehawk** [comment]
@eshmanev 
try the following freshly scaffolded project. works just fine over here. if it doesn't work on your machine, then it's definitely something in your setup. report back with any error messages pls.
[SourceGenRepro.zip](https://github.com/user-attachments/files/16247540/SourceGenRepro.zip)

**Comment by john-mcsweeney-stagecraft** [comment]
> I have recently faced the same problem on VS 17.8.5. Installed .NET Compiler Platform SDK and .NET 8 SDK, but it stills does not work. I have also tried to build the Web project from the FastEndpoints sources, but it has the same error.

I had the same issue and installed all additional web packages, ie. WebAssembly Build Tools, Advanced ASP.NET features, Web Deploy, and is now working

**Comment by syedrizwanmy** [comment]
This my help someone in the future, I scratched my head for a long time, spent two days figuring out what's broken. Only to realize that I don't have any Endpoints implemented in my code. I removed the example SayHello Endpoint when cleaning up project structure.

**Comment by john-mcsweeney-stagecraft** [comment]
> This my help someone in the future, I scratched my head for a long time, spent two days figuring out what's broken. Only to realize that I don't have any Endpoints implemented in my code. I removed the example SayHello Endpoint when cleaning up project structure. Implementing an Endpoint cleared the error.

It's a good point, and some people might get caught up with that error, but it is not the solution for the problems listed in this thread.
