### ISSUE TITLE
Swagger Fail to Load Definition

### ISSUE THREAD

**Issue by mikecasas** [dj-nitehawk/FastEndpoints#12]
@dj-nitehawk  Great project! Thanks for sharing.

When I use the visual studio extension and create two folders each with the fileset, Swagger can't load the definition. It works fine when I create the first folder, but adding the second one seems to crash it.

Below is my folder structure.

![swagger1](https://user-images.githubusercontent.com/11261164/146583112-bcc9b300-001e-4316-84fc-989ca7741519.PNG)

I tried changing the routes on each endpoint to make sure they were uniqe, but that didn't fix anything.

**Comment by dj-nitehawk** [comment]
you probably have a namespace conflit between your features/endpoints.

see here: https://streamable.com/dob6yo

[get the sample project here](https://github.com/dj-nitehawk/FastEndpoints/files/7738660/MyWebApp.zip)

you should do folder per feature/endpoint. group them in nested folders as shown.

let me know if you need further help...

**Comment by mikecasas** [comment]
Thanks for the video and the other links. I tried modifying my project, but it still didn't work. I am doing too many tasks at the moment.

I downloaded the sample project and it worked perfectly. So I'll look at that later.

Thanks!
