### ISSUE TITLE
Problem reflecting over .NET Framework assemblies

### ISSUE THREAD

**Issue by jvetter713** [dj-nitehawk/FastEndpoints#121]
I'm working on a Minimal Web API in .NET 6 that is referencing some .NET Framework assemblies that were written in VB.NET.  The Web API cannot run and the culprit exists within \FastEndpoints\Extensions\EndpointData.cs:

`
var discoveredTypes = AppDomain.CurrentDomain
            .GetAssemblies()
            .Union(assemblies)
            .Where(a =>
                !a.IsDynamic &&
                !excludes.Any(n => a.FullName!.StartsWith(n)))
            .SelectMany(a => a.GetTypes())
            .Where(t =>
                !t.IsAbstract &&
                !t.IsInterface &&
                !t.IsGenericType &&
                t.GetInterfaces().Intersect(new[] {
                        Types.IEndpoint,
                        Types.IValidator,
                        Types.IEventHandler,
                        Types.ISummary
                }).Any());
`

When a.GetTypes() is executed, it throws indicating the following:

System.Reflection.ReflectionTypeLoadException: 'Unable to load one or more of the requested types.
Could not load type 'Microsoft.VisualBasic.ApplicationServices.ApplicationBase' from assembly 'Microsoft.VisualBasic, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
Could not load type 'Microsoft.VisualBasic.Devices.Computer' from assembly 'Microsoft.VisualBasic, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.'

I realize that asking for a fix to address assemblies written in VB.NET on .NET Framework will not be a high priority for you.  That said, I would like to ask for some way to tell FastEndpoints to not reflect over every assembly within the Extension Method called AddFastEndpoints.  Maybe an overload to explicitly provide the assemblies to reflect over?  Maybe an overload to only reflect over the Executing Assembly with the option to provide additional assemblies?

Thank you for your consideration.

Jason

**Comment by dj-nitehawk** [comment]
can you give `v4.2.1-beta2` a try?
you can now turn off auto scanning and provide the assemblies to be scanned like so:
```csharp
builder.Services.AddFastEndpoints(new()
{
    DisableAutoDiscovery = true,
    Assemblies = new[]
    {
        typeof(MyNamespace1.MyEndPoint1).Assembly,
        typeof(MyNamespace2.MyEndPoint2).Assembly
    }
});
```
alternatively you can keep auto discovery on and filter out unwanted assemblies by specifying a predicate like so:
```csharp
builder.Services.AddFastEndpoints(new()
{
    AssemblyFilter = a => a.FullName!.StartsWith("MyProject")
});
```

**Comment by jvetter713** [comment]
I'll try it now.  Thank you!

**Comment by dj-nitehawk** [comment]
alright will look in to that
