### ISSUE TITLE
Swagger-FluentValidation integration not working for child objects

### ISSUE THREAD

**Issue by wjax** [dj-nitehawk/FastEndpoints#127]
As mentioned in https://github.com/dj-nitehawk/FastEndpoints/issues/89#issuecomment-1133554094
and https://github.com/dj-nitehawk/FastEndpoints/pull/126#issue-1243758749

There are still two main things not working properly for a correct validation rules in swagger:

* Not adding to schema properties in child objects. Example `RuleFor(x => x.baseid.Identifier).NotEmpty();`
* Not adding to schema `RuleFor(x => x.baseid).SetValidator(new BaseIdentifierValidator());`

**Comment by NeskireDK** [comment]
Wow, that was quick @wjax, although I see no improvement in validation schema. 
I just did a quick test on both my main project and the playground (wjax version). 
I updated to 4.3-beta3 for both FastEndpoints and FastEdnpoints.Swagger. 

Unfortunately i'm not much available the next following days. But i can chip in this weekend.

**Comment by NeskireDK** [comment]
![image](https://user-images.githubusercontent.com/10115530/169972722-3112cec0-8860-4703-9c33-4b609ba61380.png)
I would expect to see the FluentValidation rules here like configured below. There should be requirement flags* for children, and length.
```csharp
    public RequestValidator() : base()
    {
        RuleFor(x => x.requestIdOriginallyCamelCase).NotEmpty();
        RuleFor(x => x.Child.ChildMesage).NotEmpty();
        RuleFor(x => x.ChildWithInheritance.ChildMesageWithInheritance).NotEmpty();
        RuleFor(x => x.BaseRequestId).NotEmpty();
        RuleFor(x => x.ChildBase.Message).NotEmpty();
        RuleFor(x => x.childBaseWithInheritance.MessageChildBaseWithInheritance).NotEmpty();
        RuleFor(x => x.childBaseWithInheritance.ChildBaseMesageBase).NotEmpty();
        RuleFor(x => x.ChildWithInheritance.ChildBaseMesage).MinimumLength(120);
        RuleFor(x => x.ChildObjectForSetValidator).SetValidator(new ChildObjectForSetValidatorValidator());
        RuleFor(x => x.childBaseObjectForSetValidator).SetValidator(new ChildBaseObjectForSetValidatorValidator());
    }


```

**Comment by dj-nitehawk** [comment]
@NeskireDK 
there's a validation delay with nuget for beta4
https://www.nuget.org/packages/FastEndpoints.Swagger/4.3.0-beta4
test with beta4 when it's out. should do the trick ;-)

**Comment by wjax** [comment]
Exactly, either you reference the projects directly from master (thats what I did while developing) or wait for beta4.

Swagger will read all super complex rules and apply all of them. :)
