### ISSUE TITLE
Question: Multi-tenancy

### ISSUE THREAD

**Issue by mikecasas** [dj-nitehawk/FastEndpoints#13]
To read a header value would you just construct a pre-processor pipeline?

In my other projects I am just reading a tenant key from the header.

**Comment by dj-nitehawk** [comment]
for now you could do the following in the handler:
```csharp
var tenantID = HttpContext.Request.Headers["TenantID"][0];
```
i will add auto model binding from headers. give me a day or two...

**Comment by dj-nitehawk** [comment]
just released v2.13 with model binding support from headers.
simply decorate a dto property with the `[FromHeader]` attribute. 
if header key/name is different to the name of the property being bound to, use the overload `[FromHeader("tenant-key")]`
same principle as [FromClaim] attribute.

**Comment by mikecasas** [comment]
Great job!
