### ISSUE TITLE
Override default 200 response metadata in Swagger

### ISSUE THREAD

**Issue by paulczy** [dj-nitehawk/FastEndpoints#14]
I have endpoints that do not always return a 200 status and I would like the Swagger docs to reflect that. 

I have no problem adding other status via the endpoint options RouteHandlerBuilder. 
``` c#
    public override void Configure()
    {
        Post("/api/vendors");
        Options(b => b
            .Produces<VendorCreateResponse>(StatusCodes.Status201Created)
            .ProducesProblem(StatusCodes.Status500InternalServerError));
    }
```

The issue is there aways a default 200 status being added to the produces metadata collection.

![image](https://user-images.githubusercontent.com/15675118/147716412-e58ab5f7-6c0c-4f2a-b190-d2034fd61645.png)

Looking at source I see it being done here:

https://github.com/dj-nitehawk/FastEndpoints/blob/85421ae5cf28b94bf8e9b414d2c63cf14d53f269/Src/Library/Endpoint.Setup.cs#L91

Has there been any thought on disabling this default behavior?

Thank you -Paul

**Comment by dj-nitehawk** [comment]
starting from `v2.18.0-beta1` you can now use the [Describe() method](https://fast-endpoints.com/wiki/Swagger-Support.html#describe-your-endpoints) in config which will clear the defaults. 

thanks for getting in touch!

**Comment by paulczy** [comment]
Perfect, just what I was looking for. Thank you for the quick response.
