### ISSUE TITLE
Cannot bind parameter from URL

### ISSUE THREAD

**Issue by nghiepvo** [dj-nitehawk/FastEndpoints#143]
I have an API as below:

host/api/product/getProductByCategory/smart phone

The request model will be got "smart phone" value with 4.0.0 version, but when I upgrade 4.2.0 version, it was not working.

**Comment by dj-nitehawk** [comment]
sorry it's not enough information to help you.
please provide code that reproduces the issue you're experiencing.

**Comment by nghiepvo** [comment]
let look on my debug:

![image](https://user-images.githubusercontent.com/47117818/170887837-0b643d13-f9a5-4504-aa10-0518190d3477.png)

![image](https://user-images.githubusercontent.com/47117818/170887902-68971969-8ca4-4796-ba09-8864ff0fa5b3.png)

![image](https://user-images.githubusercontent.com/47117818/170887971-9eda6e16-4ca0-4a92-959f-8c3c8413fe4b.png)

**Comment by dj-nitehawk** [comment]
fixed in `v4.3.0-beta9` thanks for reporting
