### ISSUE TITLE
Cannot run test when add reference from from other project

### ISSUE THREAD

**Issue by nghiepvo** [dj-nitehawk/FastEndpoints#145]
![image](https://user-images.githubusercontent.com/47117818/171208073-33ae6069-f23d-47c2-895c-1a183e79ee3a.png)

I have a structure as bellow

1. Common (Class Library) project and added FastEndpoints
2. API project and added reference from Common.
when run testing on solution.
`dotnet test solution.sln --collect:"XPlat Code Coverage"`

it's only working when run test inside API project.

when I used FastEndpoints on only API project, it's working

I think we should investigate, it's important for run CI on real application

**Comment by dj-nitehawk** [comment]
i don't think this has anything to do with FastEndpoints. 
we have many projects using CI/CD and haven't come across anything like this.
looks like some misconfiguration/misuse of sonar qube by the looks of it.

**Comment by nghiepvo** [comment]
![image](https://user-images.githubusercontent.com/47117818/171220658-604a7ef5-696b-46b9-baf7-0b6ee2451535.png)
thank you your response.

I just remove sonar configuration.

**Comment by dj-nitehawk** [comment]
can you make a small repro solution with just 1 sample endpoint and 1 test?
zip it up and attach it here.
i will have a look.
this is most likely a project misconfiguration issue where it can't find `fastendpoints.dll` for some reason.

**Comment by nghiepvo** [comment]
https://github.com/nghiepvo/microservice-netcore6

you can look on it. it's a demo with my team

so sorry, because I also want to review your project, it's so great, and I only want to make sure when apply your project with my next project with my team, thank you so much for support.

**Comment by dj-nitehawk** [comment]
corrected the csproj files and sent in a PR to your repo: https://github.com/nghiepvo/microservice-netcore6/pull/1
tests are running file now:
![screen-record-1654017876](https://user-images.githubusercontent.com/7043768/171235811-25639504-8939-43e2-8c91-26e1cccd7531.png)

**Comment by nghiepvo** [comment]
@dj-nitehawk  many thanks
