### ISSUE TITLE
Add app registration order to the documentation.

### ISSUE THREAD

**Issue by KnightSwordAG** [dj-nitehawk/FastEndpoints#146]
So I'm developing a blazor application with FastEndpoints as the backend, and I was consistently running into a CORS issue, even though CORS was configured. I was able to resolve this problem by reviewing your example code and noticing that CORS middleware calls should be made before the UseFastEndpoints call, and doing so solved all my problems, but I feel this should be added to the documentation somewhere? Just a suggestion.

**Comment by dj-nitehawk** [comment]
yeah it's typically ordered like so:

https://github.com/dj-nitehawk/FastEndpoints/blob/8c45b66d6745927fcc45bb2a33f95c17dfe52f82/Web/Program.cs#L62-L66

will add to docs.

thanks!

**Comment by KnightSwordAG** [comment]
Yes, that's precisely the issue I ran into. Thank you!

**Comment by iAmBipinPaul** [comment]
same here
