### ISSUE TITLE
Delete request with parameter doesn't work

### ISSUE THREAD

**Issue by poplooukhinalexander** [dj-nitehawk/FastEndpoints#152]
I have route DELETE /admin/providers and this route work properly.
If I use route DELETE /admin/providers/{Id} I get error 404  Not Found.
```csharp
    public class Request
    {      
        public Guid Id { get; set; }
    }

    public class Endpoint : Endpoint<Request>
    {      
        public override void Configure()
        {
            Delete("/admin/providers/{Id}");          
            AllowAnonymous();
        }

        public override async Task HandleAsync(Request req, CancellationToken ct)
        {
            await SendNoContentAsync(ct);
        }
    }
```
I have route for GET /admin/providers/{Id} and all right.

**Comment by dj-nitehawk** [comment]
can you tell me how i can replicate it?
works fine with what you posted: https://streamable.com/ep146k

**Comment by poplooukhinalexander** [comment]
I setup endpoint: Delete("/admin/providers") and use Handler as:
` public override async Task HandleAsync(CancellationToken ct)
  {
      await SendNoContentAsync(ct);
  }
`
Request 
`curl -X 'DELETE' \
  'http://localhost:44424/admin/providers' \
  -H 'accept: text/plain'
` returns 204.

If I setup endpoint:
`
public class Endpoint : Endpoint<Request>
    {

        public override void Configure()
        {          
           Delete("/admin/providers/{Id}");           
        }

        public override async Task HandleAsync(Request req, CancellationToken ct)
        {
            await SendNoContentAsync(ct);
        }
    }
`
where Request is:
`
 public class Request
    {      
        public Guid Id { get; set; }
    }
`
I always got error 404 when I send request:
`curl -X 'DELETE' \
  'http://localhost:44424/admin/providers/3c8b8d4a-b387-4d05-a3ef-7e3019eadeee' \
  -H 'accept: application/json'
`

**Comment by dj-nitehawk** [comment]
still can't replicate.
can you pls update the following project and send back?
[TestDelete.zip](https://github.com/dj-nitehawk/FastEndpoints/files/8926378/TestDelete.zip)

**Comment by Stallion8472** [comment]
I am having the same issue with delete requests getting a 404. The difference in configuration for me is that the application is also serving a static app with app.MapFallbackToFile("index.html"). Commenting that line out and everything works as expected (besides that app of course not serving the static files). Don't know if there is some configuration that needs to be done to enable both to work as expected. Not sure why its only happening for delete requests. Any insight would be great.

**Comment by dj-nitehawk** [comment]
@Stallion8472 pls update the following project to replicate your issue and send back.
[TestDelete.zip](https://github.com/FastEndpoints/FastEndpoints/files/10728640/TestDelete.zip)

**Comment by Stallion8472** [comment]
Thank you for providing the test project. I was able to replicate the issue by dropping the version to 5.1.0 which is what I was currently working with and rearranging the program.cs file to match mine. Upgrading to the latest 5.7.2 does seem to solve the issue. Again thanks for taking your time to help and also for making this whole project.
