### ISSUE TITLE
API versioning in .../v{version:apiVersion}/... format

### ISSUE THREAD

**Issue by sajadafaghiy** [dj-nitehawk/FastEndpoints#158]
It will be great option if we can versioning the each API in .../v{version:apiVersion}/... format.

For example :
`- api/v1/admin/login`
`- api/v2/admin/login`

and it can be configured in the configure method as:
```
public override void Configure()
{
  ...
  Version(2);
  Routes("/api/v{version:apiVersion}/admin/login");
  ...
}
```

In this way, there is no need to define a prefix or suffix.

**Comment by dj-nitehawk** [comment]
this would require a complete rework of the versioning system, which i'm not willing to undertake anytime soon. also it would break all existing code. maybe someone else can look in to it. i'll keep this issue open as a feature request.
anybody working on it MUST make sure that no existing code will break.
thanks for the suggestion...

**Comment by lommez** [comment]
Any updates about this feature?

**Comment by dj-nitehawk** [comment]
we now have `Asp.Versioning.Http` package support: https://fast-endpoints.com/docs/api-versioning#asp-versioning-http-package-support-experimental
