### ISSUE TITLE
Using Fast Endpoints with FluentResults

### ISSUE THREAD

**Issue by RHaughton** [dj-nitehawk/FastEndpoints#159]
First of all, I love this library.

I point I dislike is the throwing of exceptions for flow control. I would love to be able to return Results like for example with FluentResults.

Is there a way to do this with the current state of the library??

Many thanks for your help

**Comment by dj-nitehawk** [comment]
are you refering to [this try/catch of the internal code](https://github.com/dj-nitehawk/FastEndpoints/blob/main/Src/Library/Endpoint/Endpoint.cs#L18-L63)  or something else.

the end user code is not supposed to be throwing exceptions. user is just supposed to add validation errors which will automatically get serialized to json.

hadn't heard of `FluentResults` before. had a quick look, but i don't really see how it can improve handler logic of an endpoint.
it does make sense however for deeper layers of your application/domain code.

maybe a code sample of how you'd like it to be may explain things a bit clearer.

**Comment by RHaughton** [comment]
How can I stop execution of the HandleAsync without throwing an exception?

         public override async Task HandleAsync(Request req, CancellationToken ct)
         {
            if (await _db.Sdgs.AlreadyExists(req.Id, ct))
                AddError(request => request.Id, "Sdg already exists");

            if (await _db.Sdgs.AlreadyExists(req.Name, ct))
                AddError(request => request.Name, "Sdg already exists");

            var sdg = Map.ToEntity(req);

            var validationResult = await _validator.ValidateAsync(sdg, ct);
            if (!validationResult.IsValid)
                ValidationFailures.AddRange(validationResult.Errors);

            ThrowIfAnyErrors();
            // How do I stop execution here without throwing an exception?
            // await SendErrorsAsync(); doesn't stop execution

            await _db.Sdgs.AddAsync(sdg, ct);
            await _db.SaveChangesAsync(ct);

            await SendOkAsync(new Response { Id = sdg.Id }, ct);
        }

**Comment by dj-nitehawk** [comment]
simply use a `return;` statement if you don't want anything below that to execute ;-)

**Comment by RHaughton** [comment]
So something like this?

        public override async Task HandleAsync(Request req, CancellationToken ct)
        {
            if (await _db.Sdgs.AlreadyExists(req.Id, ct))
                AddError(request => request.Id, "Sdg already exists");

            if (await _db.Sdgs.AlreadyExists(req.Name, ct))
                AddError(request => request.Name, "Sdg already exists");

            var sdg = Map.ToEntity(req);

            var validationResult = await _validator.ValidateAsync(sdg, ct);
            if (!validationResult.IsValid)
                ValidationFailures.AddRange(validationResult.Errors);

            if (ValidationFailures.Any())
            {
                await SendErrorsAsync(cancellation: ct);
                return;
            }

            await _db.Sdgs.AddAsync(sdg, ct);
            await _db.SaveChangesAsync(ct);

            await SendOkAsync(new Response { Id = sdg.Id }, ct);
        }
    }

**Comment by dj-nitehawk** [comment]
have you seen [this example](https://fast-endpoints.com/wiki/Validation.html#application-logic-validation) from the docs?

doing it that way is much cleaner than your code above.

and the performance impact is kinda negligible.

but yeah, the choice is yours.

also note that `ThrowIfAnyErrors()` and `ThrowError()` doesn't neccessarily mean your handler is throwing an exception. those methods just instruct fastendpoints to automatically send an error response with the current collection of validation failures, which you add to by using `AddError()` method.

hope that clears it up.

**Comment by RHaughton** [comment]
Understood. Thanks for your help.

**Comment by RHaughton** [comment]
Would this be the correct Update Handler?

        public override async Task HandleAsync(Request req, CancellationToken ct)
        {
            var sdg = await _context.Sdgs.SingleOrDefaultAsync(x => x.Id == req.Id, ct);
            if (sdg is null)
            {
                await SendNotFoundAsync(ct);
                return;
            }

            sdg.Name = req.Name;
            sdg.Description = req.Description;

            await _context.SaveChangesAsync(ct);
        }

**Comment by dj-nitehawk** [comment]
yeah looks good.
at the end you should do `SendOkAsync()` to return a 200 ok response

**Comment by RHaughton** [comment]
Could you explain when should we use the override HandleAsync vs the ExecuteAsync?

         public override async Task<ApiResponse<SdgDto>> ExecuteAsync(Request req, CancellationToken ct)
        {
            var dto = await _context.Sdgs
                .ProjectToType<SdgDto>()
                .SingleOrDefaultAsync(sdg => sdg.Id == req.Id, ct);

            if (dto is not null)
                return ApiResponse.Ok(dto);

            await SendNotFoundAsync(ct);
            return ApiResponse.Fail<SdgDto>("Sdg was not found.");
        }

vs

        public override async Task HandleAsync(Request req, CancellationToken ct)
        {
            var dto = await _context.Sdgs
                .ProjectToType<SdgDto>()
                .SingleOrDefaultAsync(sdg => sdg.Id == req.Id, ct);

            if (dto is null)
            {
                await SendNotFoundAsync(ct);
                return;
            }

            await SendOkAsync(ApiResponse.Ok(dto), ct);
        }

**Comment by dj-nitehawk** [comment]
it's just a matter of personal preference.
also returning the response dto can be helpful for doing unit tests.

**Comment by kcadduk** [comment]
> are you refering to [this try/catch of the internal code](https://github.com/dj-nitehawk/FastEndpoints/blob/main/Src/Library/Endpoint/Endpoint.cs#L18-L63) or something else.
> 
> the end user code is not supposed to be throwing exceptions. user is just supposed to add validation errors which will automatically get serialized to json.
> 
> hadn't heard of `FluentResults` before. had a quick look, but i don't really see how it can improve handler logic of an endpoint. it does make sense however for deeper layers of your application/domain code.
> 
> maybe a code sample of how you'd like it to be may explain things a bit better.

Sorry to re-open this closed issue, but I preferred that than opening a new issue :)

FluentResults allow me to handle Errors through the entire stack. Rather than using Exceptions to handle normal business errors, I can return failed results with N-number of errors attached each with their own context.

Consider checking the database for a single record by ID, where I want to return an error when that record does not exist. I have my method that returns a Person Object, or rather a Result<Person>. Which can be successful (or not).

If you call the `.Single()` extension method on a database for example, you will throw an exception, but the person not existing is **not exceptional** it is an expected possibility. Catching Exceptions is expensive. I actually call `.SingleOrDefault()` then if I returned null, I return a `Result.Fail(new NotFoundError())` from that method, or simply the person as a `Result.Success(person)`. Which as it travels up the stack, can prevent other code from running, because I have a failed result. When it reaches the endpoint, I can then decide what to do with the error in the endpoint. If it is Not Found Error, return 404. I can return 400 if it is another error, or if I wasn't able to understand the specifics of the error in the endpoint, return a 500. 

I'd be interested in trying to see if these libraries could work together in some way.
