### ISSUE TITLE
Add an Update method to the Mapper

### ISSUE THREAD

**Issue by RHaughton** [dj-nitehawk/FastEndpoints#160]
Hi,

I would love to see an update method to the Mapper.
The current mapper only allow us the new up a new Instance of the Entity. 

Mapper:

        public class MyMapper : Mapper<Request, Response, Entity>
        {
                public override Entity UpdateEntity(Request req, Entity entity)
                { 
                       // Update Logic

                       return entity;
                }
        }

**Comment by MichaelHochriegl** [comment]
Can look at this tomorrow. Anything specific I should adhere to? I would have implemented it the same way as the other maker Mapper functions.

Any manning convention? "UpdateEntity" ok?

**Comment by dj-nitehawk** [comment]
yeah `UpdateEntity()` sounds ok...
cheers!
