### ISSUE TITLE
Cannot use due to automatic filtering of all assemblies starting with "Microsoft"

### ISSUE THREAD

**Issue by VanessaRussell** [dj-nitehawk/FastEndpoints#162]
I was really excited and eager to use this project in a new webapp that our team is building here at Microsoft. Unfortunately, as things currently stand, I am not able to. It makes sense to exclude the Microsoft framework assemblies from scanning; however, the current logic is unintentionally also excluding our custom webapp assemblies. This is because even our internal custom assembly names are also required to start with "Microsoft".

I would like to propose a solution where any specified assemblies via the `EndpointDiscoveryOptions.Assemblies` prop would bypass the hard coded exclusion check. In that way, I can pass in the "Microsoft.MyWebApp" assembly and it will still get scanned while the "Microsoft.AspNetCore.Authorization" assembly would still get excluded as desired.

If I submit a PR with the proposed changes, would you be willing to consider merging it in?

**Comment by dj-nitehawk** [comment]
thanks for bringing this to our attention.
`v4.3.1` has been released with a fix.
now you can do:
```csharp
builder.Services.AddFastEndpoints(o =>
{
    o.DisableAutoDiscovery = true;
    o.Assemblies = new[] { typeof(Microsoft.MyWebApp).Assembly };
});
```
