### ISSUE TITLE
Uploading binary and and media type not supported (415)

### ISSUE THREAD

**Issue by freenetbrasil** [dj-nitehawk/FastEndpoints#164]
Hi,

We are starting to use Fast Endpoints and it's working great, nice job.

Currently we post using HttpClient a binary body using:

```
var content = new StreamContent(mystream);
content.Headers.Add("Content-Type", "application/octet-stream");
var response = await _http.PostAsync($"https://....../", content).ConfigureAwait(false);

```

The problem is that whenever I add the Content Type I get a 415 from the Fast Endpoint not even calling the HandleAsync, the  Configure is as follows:

```
 public override void Configure()
        {
            Verbs(Http.POST);
            Routes("myendpoint");
            AllowAnonymous();
        }
```
If I remove the header Content Type, evrything works fine.

Maybe I'm missing anything or is this an issue?

Thanks

**Comment by dj-nitehawk** [comment]
you need to add the content type to the accepts metadata of the endpoint like so:
```csharp
public override void Configure()
{
    Post("myendpoint");
    AllowAnonymous();
    Description(b => b.Accepts<Request>("application/octet-stream"));
}
```
because by default only "application/json" is allowed
