### ISSUE TITLE
Documentation suggestion

### ISSUE THREAD

**Issue by metscore** [dj-nitehawk/FastEndpoints#166]
Hello,

First of all, let me say how pleased I am with FastEndpoints. I've been trying it out now for some time (after seeing Nick Chapsas video) and being a newbie when it comes to REST api, I'm really, really pleased with it.

Something that I've been looking for, but been unable to find is a small example of a convenient way of sending binary data from one application to my REST api FastEndpoint. I've tried (using Postman and form-data) to send a binary file, which works fine, but it would be really cool if there was a small tutorial on how to send/receive binary data that does not originate from a file. (There is a binary part of the body that maybe can be used as opposed to the form-data).

King regards
Magnus

BTW: I'm sorry if this is the incorrect form of suggesting this. Please advice if there is an alternative area for posting this question/suggestion.

**Comment by dj-nitehawk** [comment]
what is the client you want to use for uploading the binary data? 

.net httpclient or something like that? 

or web browser fetch client? etc.

**Comment by metscore** [comment]
Thanks for the quick answer !!  :-)

I apologize for not being more clear. Basically the idea is to write a client application would use the restAPI to send instantiated classes (which obviously would have to be serialized) over the wire to the server which could then would de-serialize the data and execute functions on the re-created class on the server side.

When come to think of it, maybe I should just use a serializer and encode the class to base64 and send it like a member in a normal request type ?

**Comment by nefarius** [comment]
Sounds like RPC to me. Like [gRPC](https://docs.microsoft.com/en-us/aspnet/core/grpc/?view=aspnetcore-6.0)?

**Comment by metscore** [comment]
Thanks for the suggestion nefarius,

I'll just elaborate a little.
I already have Proto.Actor internally for some code which is in turn is gRPC below the surface. I know, totally overkill in this case since if I'm not mistaken more for microservices.
Anyway, I was asked to provide a REST api and I did create that. So far so good, but then the requirement changed and I need to handle binary data as well. Instead of revamping it all to gRPC I thought I could just add one "binary function" to keep the REST api (which is convenient for running small stuff using a web browser) but if the the guy who requested the binary approach would want to run that functionality he would have to write his own application.

I just did some small testing and maybe it is quite sufficient to code the class to json (using Newtonsoft or whatever) and then base64 code that and then receive that data using a regular request dto, process the data on the server and then respond with a response dto to the client side.
Obviously the client and the server would have to share the common object, but that is not a problem.
Of course, doing it all from scratch maybe another approach would have been better (gRPC) but I am where I am now...  ;-)

I almost feel like an idiot for disturbing you guys with such a trivial matter. My apologies !

King regards
Magnus

**Comment by dj-nitehawk** [comment]
just use [HttpClient](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=net-6.0)

endpoint and shared dto/object:
```csharp
public class MySharedObject
{
    public int Id { get; set; }
    public string Name { get; set; }
}

public class MyEndpoint : Endpoint<MySharedObject>
{
    public override void Configure()
    {
        Post("/api/test");
        AllowAnonymous();
    }

    public override async Task HandleAsync(MySharedObject req, CancellationToken ct)
    {
        Console.WriteLine(req.Name);
        await SendAsync("all good " + req.Name);
    }
}
```

in client application, just do this:
```csharp
var client = new HttpClient();

await client.PostAsJsonAsync("http://mysite.com/api/test", new MySharedObject { Id = 1, Name = "test" });
```
