### ISSUE TITLE
Grabbing live data for the swagger example data

### ISSUE THREAD

**Issue by OFark** [dj-nitehawk/FastEndpoints#168]
My API lives behind an APIKey middleware authorisation.  A 500 is returned if the APIKey is not found in either the request URL, header or Cookie. This includes the Swagger UI. So I have a Cookie injected on success so you no longer need to keep specifying the APIKey on every UI call. 

I would ideally like to have Swagger already know your APIKey, fill it in the X-API-Key Header input as an Example from the cookie. I was trying to use ExampleRequest but that's built on App startup and there is no HTTPContext. 

So I have the APIKey in a Cookie and I have it in a Middleware service, any idea how I could get Swagger to show this as an example?

**Comment by dj-nitehawk** [comment]
i don't think it's possible with nswag because the swagger docs are only built once at startup and cached for the duration of the app lifetime.

you might be able to inject some javascript in to swagger that will read your api key from the cookie and sets it in ui. 
i have no idea how to do that though.

the injection part can be done like so:
```csharp
app.UseSwaggerUi3(s =>
{
    s.ConfigureDefaults();
    s.CustomJavaScriptPath = "apiKeyInjector.js";
});
```

**Comment by OFark** [comment]
I'll leave this here for anyone else wanting to do something similar. 
After adding a reference to a JS file as noted above by @dj-nitehawk if you add the following to your JS file it will load in a cookie. 
Swagger renders an initially blank page, the DOM is then created via JS, and subsequent expansions of panels are further additions to the DOM, so you need to listen for DOM changes.

The two functions are standard code from SO/W3schools, but logic is in the function passed to docReady.

You can change the values accordingly to affect different fields by changing the "data-param-name" value to the field.
 
```
function docReady(fn) {
    // see if DOM is already available
    if (document.readyState === "complete" || document.readyState === "interactive") {
        // call on next available tick
        setTimeout(fn, 1);
    } else {
        document.addEventListener("DOMContentLoaded", fn);
    }
}  

function getCookie(cname) {
    let name = cname + "=";
    let decodedCookie = decodeURIComponent(document.cookie);
    let ca = decodedCookie.split(';');
    for (let i = 0; i < ca.length; i++) {
        let c = ca[i];
        while (c.charAt(0) == ' ') {
            c = c.substring(1);
        }
        if (c.indexOf(name) == 0) {
            return c.substring(name.length, c.length);
        }
    }
    return "";
}

docReady(function () {
    document.body.addEventListener('DOMNodeInserted', function (evt) {
        if (evt.target.className == 'opblock-section') {
            evt.target.querySelectorAll('tr[data-param-name="X-API-Key"]').forEach(function (el) {
                var input = el.querySelector('input');
                input.value = getCookie("X-API-Key");
            });
        }
    });
});
```
