### ISSUE TITLE
Passing Parameter to PreProcessor

### ISSUE THREAD

**Issue by bryanllewis** [dj-nitehawk/FastEndpoints#169]
I have been trying to use some middleware and the Permissions method to handle some custom security logic that we have, but it's just not working quite the way I want.  I turned to the possibility of using a Pre-Processor and something like your SecurityProcessor example.  However, I need to pass in a string to the Pre-Processor and it does not appear that you can pass any parameters, only access the context and request object.  Is there any way around this limitation?  The string will not be in the header or request -- it will be similar to defining a permission string in the endpoint class like what is passed into the Permissions method.
Thanks,
Bryan

**Comment by dj-nitehawk** [comment]
does the string/value in question need to be a different one per each request? 
or is it going to be the same for the whole duration of the app lifetime?

if the case is the latter, simply pass it in as a constructor argument to the pre-processor. because the `Configure()` method is only called once at startup and pre-processors are singletons.

if the case is the former, you could pass it in via the `HttpContext.Items` dictionary or add it as a property to the request dto.

if that doesn't really solve it, pls show me some code so i can understand what you're trying to achieve.

**Comment by wjax** [comment]
Hi Bryan,

We use a derived Endpoint class that we call SecureEndpoint.
Those SecureEndpoints use a Preprocessor that accepts a list of "Needed Permissions" that need to be checked by against an IAMish service.

So we use it like this
```csharp
    public override void Configure()
    {
        Get($"{EndpointConfiguration.BaseRoute}/list-by-user");
        Version(1);
        NeedsPermission(Permission.ListByUser<RequestContext<GetPermissionsByGranteeRequest>>(
            x => x.Request.User,
            x => x.Request.Context));

        base.Configure();
    }
```

`NeedsPermission` accepts an object of type Permission that defines some things like the intended action and some per-request data to populate the Permission that finally gets checked against the IAM. For this matter, we pass some `Func` that "knows" how to get certain data from the `Request`

Does it help?

**Comment by dj-nitehawk** [comment]
@wjax 
> ```cs
> EndpointConfiguration.BaseRoute
> ```
is [global route prefix](https://fast-endpoints.com/wiki/Configuration-Settings.html#global-route-prefix) not a good fit for this?

**Comment by wjax** [comment]
> @wjax 
> 
> > ```cs
> 
> > EndpointConfiguration.BaseRoute
> 
> > ```
> 
> is [global route prefix](https://fast-endpoints.com/wiki/Configuration-Settings.html#global-route-prefix) not a good fit for this?
> 
> 

Not really. That BaseRoute is different for every "service" under this api. They are under different namespaces

**Comment by dj-nitehawk** [comment]
ah i see...
all good then ;-)

**Comment by bryanllewis** [comment]
@dj-nitehawk 

Thank you for the suggestions.  While I was originally hoping to keep this out of the Request object, I may go that route.  But I am looking at your HttpContext.Items suggestion first.

Bryan
