### ISSUE TITLE
Custom model binding

### ISSUE THREAD

**Issue by SpeedOfSpin** [dj-nitehawk/FastEndpoints#172]
Love this project.

Is there anyway I can add custom model binding like I can in .net core using MVC.

thanks
Erik

**Comment by dj-nitehawk** [comment]
custom model binders are not supported in minimal api atm.
so there's no support for that with FastEndpoints either.
however, you can do some level of custom binding the the static `TryParse` method mentioned [here](https://fast-endpoints.com/wiki/Model-Binding.html#from-form-fieldsroutequeryclaimsheaders)

**Comment by SpeedOfSpin** [comment]
Thank you for the quick reply.

I think that will work. :-)

Thanks again
Erik

**Comment by dj-nitehawk** [comment]
also i'm investigating adding a new attribute something like `[BindUsingJsonSerializer]` which should offload the deserializing and binding stuff to dto properties using `System.Text.Json`. let's see...

**Comment by dj-nitehawk** [comment]
`v4.4.0-beta7` adds custom model binder support per endpoint/request dto combo like so:
```csharp
public class Product
{
    public int Id { get; set; }
    public string Name { get; set; }
    public decimal Price { get; set; }
}

public class Request
{
    public string Id { get; set; }
    public Product? Product { get; set; }
    public string CustomerID { get; set; }
}

public class Binder : IRequestBinder<Request>
{
    public async ValueTask<Request> BindAsync(BinderContext ctx, CancellationToken ct)
    {
        // populate and return a request dto object however you please...
        return new Request
        {
            Id = ctx.HttpContext.Request.RouteValues["id"]?.ToString()!,
            CustomerID = ctx.HttpContext.Request.Headers["CustomerID"].ToString()!,
            Product = await JsonSerializer.DeserializeAsync<Product>(ctx.HttpContext.Request.Body, new JsonSerializerOptions(), ct)
        };
    }
}

public class Endpoint : Endpoint<Request, Response>
{
    public override void Configure()
    {
        Post("/test-cases/custom-request-binder");
        RequestBinder(new Binder());
    }

    public override Task HandleAsync(Request r, CancellationToken c)
    {
        ...
    }
}
```
