### ISSUE TITLE
Versjoning configuration

### ISSUE THREAD

**Issue by WojciechNagorski** [dj-nitehawk/FastEndpoints#175]
There is a description on page https://fast-endpoints.com/wiki/Api-Versioning.html that FastEndpoints adds a version at the end of URL:

```
- /admin/login
- /admin/login/v1
- /admin/login/v2
- /inventory/order/{OrderID}
- /inventory/order/{OrderID}/v1
```

I would prefer a different format, with putting the version at the beginning of URL
```
- api/admin/login
- api/v1/admin/login
- api/v2/admin/login
- api/inventory/order/{OrderID}
- api/v1/inventory/order/{OrderID}
```
Is it possible in FastEndpoints?

**Comment by dj-nitehawk** [comment]
see here: https://fast-endpoints.com/wiki/Api-Versioning.html#versioning-options
set `SuffixedVersion` to false

**Comment by WojciechNagorski** [comment]
Thanks for the quick reply. I've added a PR to documentation #176.
