### ISSUE TITLE
Able to have a base configure for Endpoints

### ISSUE THREAD

**Issue by stefandevo** [dj-nitehawk/FastEndpoints#18]
If I want specific behaviour for a set of endpoints (like AuthorizedEndpoint, AnonymousEndpoint, CustomerEndpoint) I would like to implement some base methods in override Configure(). However, I would like to have the option to have a kind of PreConfigure virtual method on the Endpoint classes so that I do not have to use base.Configure() in each Configure method of all these implementations.
Thx.

**Comment by dj-nitehawk** [comment]
you can already do it. just use the base class ctor to do your preconfiguration like so:
```csharp
public class UpdateCustomerEndpoint : AuthorizedEndpoint<EmptyRequest, EmptyResponse>
{
    public override void Configure()
    {
        Post("/customer/update");
    }

    public override Task HandleAsync(EmptyRequest req, CancellationToken ct)
    {
        return SendStringAsync("hello...");
    }
}

public abstract class AuthorizedEndpoint<TRequest, TResponse> : Endpoint<TRequest, TResponse>
    where TRequest : class, new()
    where TResponse : notnull, new()
{
    protected AuthorizedEndpoint()
    {
        Permissions("ModifyCustomer");
        Claims("AdminID");
    }
}
```

**Comment by stefandevo** [comment]
Ok; I was not aware that everything you set in `Configure` can be set in the constructor as well. Great!
