### ISSUE TITLE
Pipeline

### ISSUE THREAD

**Issue by Zsolt-Bendes** [dj-nitehawk/FastEndpoints#2]
I have a feature request if it's possible, please consider adding api for adding pipeline behaviors.
I can suggest [Brighter](https://github.com/BrighterCommand/Brighter) as good library to achieve this with annotations.

**Scenario**:
As a DDD developer I want to hook up pipeline behaviors before and after the execution of a Handler.

Usage examples:

- adds logging before and after each request
- adds the ability to dispatch side effects after my handler succeeds, but before the changes are committed to the database
- adds the ability to start a transaction before the handler, and commit transaction after the handler

**Comment by neozhu** [comment]
That's a good point. as like MidiatR,?

**Comment by dj-nitehawk** [comment]
done...

here's what a [pre-processor](https://github.com/dj-nitehawk/FastEndpoints/blob/main/Web/PipelineBehaviors/PreProcessors/MyRequestLogger.cs) and [post-processor](https://github.com/dj-nitehawk/FastEndpoints/blob/main/Web/PipelineBehaviors/PostProcessors/MyResponseLogger.cs) looks like.

all you gotta do is then register them [like this](https://github.com/dj-nitehawk/FastEndpoints/blob/747b13b00d052ad2d841fb8d11f09e1193cd4565/Web/%5BFeatures%5D/Sales/Orders/Create/Endpoint.cs#L13)
