### ISSUE TITLE
FromHeader/FromClaim documentation bug

### ISSUE THREAD

**Issue by stefandevo** [dj-nitehawk/FastEndpoints#20]
In the docs https://fast-endpoints.com/wiki/Model-Binding.html there are samples of

```
[FromHeader("tenant-id")]
public int TenantID { get; set; }

[FromClaim("user-id")]
public int UserID { get; set; }
```

However, it seems that only `string` types are supported for these attributes. When running it gives:

```
[FromHeader] attributes are only supported on string properties!
```

exception.

**Comment by dj-nitehawk** [comment]
good catch!
fixed...
and thank you!
really appreciate the feedback you're giving 🙏
