### ISSUE TITLE
Wrong swagger generation

### ISSUE THREAD

**Issue by stefandevo** [dj-nitehawk/FastEndpoints#21]
I think following request object:

```
public class Request
{
	[FromHeader("tenant-id")]
	public string TenantID { get; set; }

	[FromClaim("user-id", isRequired:false)]
	public string UserID { get; set; }
}
```

is generating a wrong swagger doc:

<img width="539" alt="image" src="https://user-images.githubusercontent.com/1656051/149930193-74db4fa5-0244-4349-bd0e-4bd56627281d.png">

I would think the `TenantID` query parameter should not be there; even filling in the parameter would not set the correct value (and I think it should be settable at all).

**Comment by dj-nitehawk** [comment]
yep this doesn't look right. will look in to it tomorrow. shouldn't be too difficult to fix.

**Comment by dj-nitehawk** [comment]
fixed in beta9
