### ISSUE TITLE
EndpointExclusionFilter, extra attributes possible?

### ISSUE THREAD

**Issue by stefandevo** [dj-nitehawk/FastEndpoints#22]
Building further on the `EndpointExclusionFilter` possibility.

Reason for using this (in my case) is to exclude certain endpoints at runtime. Based upon an environment setting you can deploy multiple versions of the same Modular Monolith solution with a subset of the endpoints.

I am now able to this, but basically only based upon an attribute I set on the endpoint; 

`[Project("Api1")]`

```
app.UseFastEndpoints(exclusionFilter: endpoint =>
{
	var attributes = endpoint.EndpointType.GetCustomAttributes(typeof(ProjectAttribute), false);
	if (attributes.Length == 0) return true; // =exclude
	var attribute = (ProjectAttribute)attributes[0];
	if (attribute.Names.Contains(envApiName)) return false;
	return true;
});
```

(*) Note this was before the change of `config.EndpointExclusionFilter`

However, I now feel I am dealing with attributes again :-)

So would it be possible to have an extra property on EndPoint that is also passed to the function?
I was thinking of a `string Metadata` property that can be set on the EndPoint. Its generic enough to set it to anything you would like to check possibly (if you want to add a comma separated list, or json, you can put it into the MetaData property).

This would ease the ExclusionFilter -> 

```
config.EndpointExclusionFilter = ep => ep.MetaData.Contains(Environment.GetEnvironmentVariable("api-name")); 
```

although I think it needs to be 

```
config.EndpointExclusionFilter = ep => !ep.MetaData.Contains(Environment.GetEnvironmentVariable("api-name")); 
```

as currently you have to return `true` to exclude it :-)

Is this something you would consider?

**Comment by mikecasas** [comment]
If I followed correctly, this could be useful for multi-tenancy, where you want client1 to a have access to a set of endpoints, but client2 has access to a different set of endpoints.

**Comment by stefandevo** [comment]
Yes, that could be a case, but it could also be possible to have two different API deployments; one with a set of endpoints, the other with another set of endpoints. 

api1.domain.com
api2.domain.com

where each could share a set, but also have their own api's specifically.

same you can do for different tenants, but most of the time that would give them the same set of api's but with different permissions for example.

but there will be cases where you have different endpoints for client1 and client2.

but basically, a way to attribute and endpoint with "something" so you can filter based upon this property. That's why I would make it a more generic property to filter on - and I think a string value is the easiest.

**Comment by dj-nitehawk** [comment]
@stefandevo with `beta7` you can now specify tags for an endpoint like so:
```csharp
public override void Configure()
{
    Tags("api1", "exclude")
}
```
also the filter return value has been inverted. now if `false` the ep will be excluded as requested.
https://github.com/dj-nitehawk/FastEndpoints/blob/f8ed39cba2c01a45a14e566263cad84842cac0a6/Web/Program.cs#L27

**Comment by stefandevo** [comment]
Thanks! This is perfect!
