### ISSUE TITLE
Serializer option

### ISSUE THREAD

**Issue by stefandevo** [dj-nitehawk/FastEndpoints#23]
Open question.

Would you consider to be able to use a different Serializer than the net core json serializer?
As you know the `System.Text.Json` is very restrictive (set a string value for an int value will cause an error) - of course a faster version than NewtonSoft.
Sometimes when the caller of the API's is not under control (not coming from your own client app) there are some considerations to make. A specific use case is an open API, or for example a web hook from FacebookMessenger where a json can contain different elements based upon a certain property. In this case NewtonSoft gives more possibilities.

As I understand, I can always use `PlainTextRequest` and do any serialisations necessary, which is already a great thing!

But as said another option could be that you could, globally set a new Serializer, or even per EndPoint if necessary.

Happy to discuss this further.

**Comment by dj-nitehawk** [comment]
will investigate if it can be done without much trouble. it is a good feature to have.

**Comment by dj-nitehawk** [comment]
with beta10 you can do following now:
```csharp
app.UseFastEndpoints(config =>
{
    config.RequestDeserializer = async (req, tDto, ct) =>
    {
        using var reader = new StreamReader(req.Body);
        return Newtonsoft.Json.JsonConvert.DeserializeObject(await reader.ReadToEndAsync(), tDto);
    };

    config.ResponseSerializer = (rsp, dto, cType, ct) =>
    {
        rsp.ContentType = cType;
        return rsp.WriteAsync(Newtonsoft.Json.JsonConvert.SerializeObject(dto), ct);
    };
});
```

**Comment by stefandevo** [comment]
perfect!
