### ISSUE TITLE
Version question

### ISSUE THREAD

**Issue by stefandevo** [dj-nitehawk/FastEndpoints#24]
Me again :-)

How would you suggest to handle versions of the API endpoints?
Not sure https://github.com/dotnet/aspnet-api-versioning this package can be used with yours.

Would it help if it was possible to have a .Version property on the endpoint (optional) as well?
And that, by convention (or trough setup), you could have /v1 or /v2.1 or whatever prefixed?

Of course, manually is also optional, just create two EndPoints and point manually to this version.

But it might me a nice optional feature to add?

Happy to discuss or collaborate on this one.

**Comment by dj-nitehawk** [comment]
minimal api does not have support for versioning yet. it's coming in .net 7 if i remember correctly.
i will investigate in the meantime if there's an easy way to do it without waiting for the next .net release.
we might have to throw away our efforts when it comes out though.
so i'll treat this as a low priority issue.

**Comment by stefandevo** [comment]
Ok thx. In the meantime I will investigate if I can prepare something that's pluggable (and can be thrown away later) :-)

**Comment by dj-nitehawk** [comment]
sounds good!

**Comment by stefandevo** [comment]
My proposal (did not make a PR, so that you can evaluate it first)

Extend class `EndpointSettings` with `internal string? Version;`

Extend class `Endpoint` in file `Endpoint.Setup` with

```
protected void Version(string version)
{
    Settings.Version = version;
}
```

In class `MainExtensions`

Add class

```
public class VersioningOptions
{
	public string DefaultVersion { get; set; }
	public string Prefix { get; set; }
}
```

In the `Config` class 

```
internal static VersioningOptions versioningOptions { get; set; } = new();

	public Action<VersioningOptions>? VersioningOptions
	{
		set => value?.Invoke(versioningOptions);
	}
```

and in `UseFastEndpoints` method add following above `var hb = builder.MapMethods(targetRoute, new[] { verb }, EndpointExecutor.HandleAsync);`

```
var targetRoute = route;
if (Config.versioningOptions is not null)
{
  var prefix = Config.versioningOptions.Prefix;
  var version = ep.Settings.Version ?? Config.versioningOptions.DefaultVersion;
  var slash = targetRoute.StartsWith("/") ? "" : "/";
  targetRoute = $"{prefix}{version}{slash}{targetRoute}";
}
```

This was it is not mandatory to use (if not set in the `UseFastEndpoints`).

If you want to use it add it to the config properties on startup:

```
	config.VersioningOptions = options =>
	{
		options.DefaultVersion = "1.0";
		options.Prefix = "v";
	};
```

then all routes will have `v1.0/` prefix for example.

In the EndPoints itself you can override in the `Configure`:

```
    public override void Configure()
    {
        Post("test-cases/plaintext/{Id}");
        AllowAnonymous();
        Version("1.1");
    }
```

You can have 2 endpoints with same route, but because of the different version it will work.


Happy to discuss it further.

**Comment by dj-nitehawk** [comment]
awesome! this looks great. 
chuck it in a PR and I will merge.
oh and don't forget to write a couple of tests that will cover the new code paths. 
thanks 🙏

**Comment by stefandevo** [comment]
Ok. Will do.

**Comment by dj-nitehawk** [comment]
@stefandevo added versioning support for swagger...

https://github.com/dj-nitehawk/FastEndpoints/blob/c3518d055e138b5f7785441a6c7df070b9d77b21/Web/Program.cs#L21-L34

**Comment by rthanga1** [comment]
@dj-nitehawk How does this work with the latest swagger package? Swagger listed all my endpoints until I enable versioning. After I enabled the versioning, swagger does not list any of my endpoints. But the endpoints are available and I can access them through postman

`builder.Services.SwaggerDocument(o =>
{
    o.DocumentSettings = s =>
    {
        s.Title = "FastEndpoints Sandbox";
        s.Version = "v1.0";
        s.DocumentName = "v1";
        s.ApiGroupNames = new[] { "v1" };
    };
});
...
app.UseFastEndpoints(c =>
{
    c.Versioning.Prefix = "v";
    c.Versioning.PrependToRoute = true;
    c.Versioning.DefaultVersion = 1;
});
`

**Comment by rthanga1** [comment]
Thanks @dj-nitehawk. It worked.
