### ISSUE TITLE
PlainTextRequest not working with json body

### ISSUE THREAD

**Issue by stefandevo** [dj-nitehawk/FastEndpoints#25]
It seems that using `PlainTextRequest` as the `Request` object only works if `Content-Type: text/plain`

However, when setting the `Content-Type: application/json` it would think that the 'BodyContent' would be filled with the body of the call - and then I can deserialise this text content. (case web hooks from external systems where you want to use NewtonSoft Json deserialiser).

When executing it I get `415 Unsupported Media Type`; it seems that the `BindToModel` in `Endpoint` is never hit - is net core itself is blocking this?

Based upon the Web project in the sources:

```
curl --location --request POST 'http://localhost:5001/test-cases/plaintext/1111' \
--header 'Content-Type: application/json' \
--data-raw '{
    "Value1": "xxx",
    "Value2": "yyyy"
}'
```

this does not work.

**Comment by dj-nitehawk** [comment]
done! works in beta8.
