### ISSUE TITLE
Routing prefix option

### ISSUE THREAD

**Issue by stefandevo** [dj-nitehawk/FastEndpoints#27]
Would love to have an option to prefix all my routes automatically through an option.

This can be come handy if you want to start all your endpoints with `api` for example if the project is used by a web application as well.

I already prepared the necessary changes, based upon the #26 - so I wait until that one is accepted/merge, and then, if you find it OK, I will create another PR with the proposed implementation.

For your reference:

https://github.com/stefandevo/FastEndpoints/commit/d1b5388c789ece0981b200bd464418f3ca85c28c

**Comment by dj-nitehawk** [comment]
awesome! #26 is merged. pls send a new pr for this one.

**Comment by dj-nitehawk** [comment]
great job!

will release the next beta in a few hours...

will also look in to how the config can be tested.

thanks again for your contributions!!!

**Comment by stefandevo** [comment]
Maybe we should think about the Wiki as well?

**Comment by dj-nitehawk** [comment]
yes i will make the neccessary updates. most likely will add a new page for config.

**Comment by dj-nitehawk** [comment]
beta11 is out with some refactoring/optimizations. pls give it a good whirl...

**Comment by stefandevo** [comment]
> beta11 is out with some refactoring/optimizations. pls give it a good whirl...

I can't see it https://www.nuget.org/packages/FastEndpoints 
Maybe I have to wait a bit more?

**Comment by dj-nitehawk** [comment]
https://www.nuget.org/packages/FastEndpoints/2.21.0-beta11

**Comment by stefandevo** [comment]
Ahhh.... it thinks beta9 is newer than beta11 :-)

**Comment by dj-nitehawk** [comment]
dang! it's actually the first time ever i've pushed a beta past 9 lol 😜
