### ISSUE TITLE
Join our Discord server for a chat!

### ISSUE THREAD

**Issue by dj-nitehawk** [dj-nitehawk/FastEndpoints#31]
if you'd like to chat with other **FastEndpoints** users, please join our discord server by [clicking here](https://discord.gg/yQZ4uvfF2E).

see you there!

**Comment by qaudaffyazmi** [comment]
The invite is no longer valid.

**Comment by dj-nitehawk** [comment]
just checked and it does still work.
here's a backup link: https://discord.gg/4up7Mk69dB

**Comment by qaudaffyazmi** [comment]
I want to confirm that both link works. It was an issue with my Discord account that made the link appear invalid.
Thanks for the fast feedback.
