### ISSUE TITLE
No operations defined in spec when using default version

### ISSUE THREAD

**Issue by stefandevo** [dj-nitehawk/FastEndpoints#35]
When setting `DefaultVersion` Swagger docs are not generated correct.

-> `No operations defined in spec` in swagger UI.

**Comment by stefandevo** [comment]
Possible related to #34 #35

**Comment by stefandevo** [comment]
Ok; that works.
Just thinking... If you set `DefaultVersion` would it be possible to have the `maxEndpointVersion` set automatically ? (if not set)

**Comment by dj-nitehawk** [comment]
i think better to let the user be explicit there. as it's a manual set of configuration for how exactly they want the swagger doc to look like. but i will give it more though.
