### ISSUE TITLE
Support file result range

### ISSUE THREAD

**Issue by vfrz** [dj-nitehawk/FastEndpoints#36]
It seems that the current version of FastEnpoints doesn't support the range HTTP header when using SendFile method.

ASP.NET controllers allow to enable range support using the `File()` method with `enableRangeProcessing` parameter: https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.controllerbase.file?view=aspnetcore-6.0#microsoft-aspnetcore-mvc-controllerbase-file(system-byte()-system-string-system-string-system-boolean)

**Comment by dj-nitehawk** [comment]
ah yes. was meaning to add support for that but forgot. will implement in the next version. shouldn't be too difficult of a task. thanks for getting in touch!

**Comment by dj-nitehawk** [comment]
`v3.2.0-beta3` released with range support. 
all file/byte/stream sending methods support range processing now.
here's a sample endpoint:

```csharp
public class Endpoint : EndpointWithoutRequest
{
    private static readonly byte[] content = Encoding.UTF8.GetBytes("abcdefghijklmnopqwstuvwxyz");

    public override void Configure()
    {
        Get("/partial/content");
        AllowAnonymous();
        Options(o => o.Produces<string>(206, "text/plain"));
    }

    public override Task HandleAsync(CancellationToken ct)
    {
        return SendBytesAsync(content, contentType: "text/plain", enableRangeProcessing: true);
    }
}
```

**Comment by vfrz** [comment]
You're working at the speed of light! Thanks a lot for this feature :)
I don't know if you want to keep the issue opened till the 3.2 release so I let you close it.
