### ISSUE TITLE
Allow parameterized ctors for events

### ISSUE THREAD

**Issue by Zsolt-Bendes** [dj-nitehawk/FastEndpoints#40]
Hi there,

I was wondering what is the reason that the event handler has a constrain for empty ctor? Is it possible maybe to change the `new()` to `notnull`?
`FastEventHandler<TEvent> : IEventHandler, IServiceResolver where TEvent : class, new()`

As a developer
Given a message with ctor that has parameters
When I need to dispatch the message
Then I'm allowed to send the message without using property setters

Example message:
```
public class MyMessage
{
    public string SomeValue { get; }
    
    public MyMessage(string someValue)
    {
        SomeValue = someValue;
    }
}
```

**Comment by dj-nitehawk** [comment]
changed to `notnull` in `v3.5.0-beta5`. should be available on nuget in a few minutes.

**Comment by Zsolt-Bendes** [comment]
Thank you.
