### ISSUE TITLE
Json source generator

### ISSUE THREAD

**Issue by Zsolt-Bendes** [dj-nitehawk/FastEndpoints#41]
Hi there,

probably remember the source generator idea. I found blog with repo where the author utilizes extension methods to use enable using the generated code. I don't remember what the issue was, but maybe helps a bit.

[The source](https://github.com/martincostello/MinimalApisWithJsonSourceGenerator)
[The blog](https://blog.martincostello.com/using-json-source-generators-with-aspnet-core-minimal-apis/)

Feels a bit premature optimalization, especially for small json payloads. But hey, could be an improvement.

**Comment by dj-nitehawk** [comment]
thanks... will look in to it.

**Comment by dj-nitehawk** [comment]
check out `v3.6.0-beta1`

here it is in action: 

https://github.com/dj-nitehawk/FastEndpoints/blob/main/Benchmark/FastEndpointsBench/CodeGenEndpoint.cs#L48

setup: 

https://github.com/dj-nitehawk/FastEndpoints/blob/main/Benchmark/FastEndpointsBench/CodeGenEndpoint.cs#L7-L9

there is no performance benefit it seems. at least for small payloads. or maybe it's not actually working. any idea how to check if the serializer context is actually being used by `system.text.json`?

**Comment by Zsolt-Bendes** [comment]
Honestly no clue. Maybe with large payload or maybe look for any `*.g.cs` . Source generators will create the generated files with `.g.cs` suffix.

**Comment by dj-nitehawk** [comment]
the g.cs files are being generated. and the serializer options that is passed in to the serializer context does seem to take effect. so I guess it's safe to assume it's working 😉

will try benchmarking with a large payload today. 

btw thanks for those links. they really helped in figuring this out.
