### ISSUE TITLE
Please make Dependency Injection more explicit for readability

### ISSUE THREAD

**Issue by aredfox** [dj-nitehawk/FastEndpoints#43]
I don't like the approach of "automagically" wiring a property, I would like control in this and have it be more explicit, so people of my team or people that take over my code know things are being injected at least, or know how a property is filled.

**Comment by dj-nitehawk** [comment]
constructor injection is presently being worked on. might be able to
release tomorrow.

**Comment by dj-nitehawk** [comment]
`v3.7.0` with constructor injection support ;-)
