### ISSUE TITLE
Make ValidationFailureException public

### ISSUE THREAD

**Issue by fauresco** [dj-nitehawk/FastEndpoints#48]
Please consider making the ValidationFailureException public so we can unit test endpoints that use "ThrowIfAnyErrors()" method.

```cshap
public async Task Webhook_OnExistingWithSameId_ReturnsErrorMessage()
{
    var e = GetEndpoint();

    // mock existing record with same id
    var w = Builder<Model.Webhook>.CreateNew().With(x => x.Id = "123").Build();
    Mock.Get(e.WebhookRepository)
        .Setup(r => r.GetById("123", default))
        .ReturnsAsync(w);

    var req = new Request
    {
        Id = "123",
        Name = "Teste",
        Description = "Webhook teste",
        Queue = "q1",
        Enabled = true
    };

    try
    {
        await e.HandleAsync(req, default);
        Assert.Fail();
    }
    catch(FastEndpoints.Validation.ValidationFailureException ex) // ValidationFailureException is internal :(
    {
        // assert proper error message for "Id"
    }
}
```

If you agree that it should be public and you are busy doing other stuff, let me know if you would like a PR.

**Comment by dj-nitehawk** [comment]
`ValidationFailureException` is not thrown. so you won't be able to `Catch` it in your test.

https://github.com/dj-nitehawk/FastEndpoints/blob/96a141990bd99a8744c9d2003225db314c305bac/Src/Library/Endpoint/Endpoint.cs#L54-L57

the way you assert validation errors is like this:

### integration test:
https://github.com/dj-nitehawk/FastEndpoints/blob/96a141990bd99a8744c9d2003225db314c305bac/Test/InventoryTests.cs#L31-L44

### unit test:
https://github.com/dj-nitehawk/FastEndpoints/blob/96a141990bd99a8744c9d2003225db314c305bac/Test/AdminTests.cs#L35-L52

**Comment by fauresco** [comment]
Thanks @dj-nitehawk, this is a lot cleaner! However, I can't make it work in the unit test. Let me know if I am missing something.

At runtime it will happens as you describe because the ExecutorMiddleware.Invoke will call internal Endpoint.ExecAsync (where the "catch(ValidationFailureException)" is located) and inside this method call ExecuteAsync or HandleAsync, so the exception will be handled by the catch block as expected. However, when unit testing we are calling Endpoint.HandleAsync directly so we do get the exception.

Here is my test:

```csharp
[TestMethod]
public async Task Webhook_OnExistingWithSameId_ReturnsHttp400AndErrorMessage()
{
    var e = Factory.Create<MinApi.Webhook.Manage.Create.Endpoint>();
    e.WebhookRepository = Mock.Of<IWebhookRepository>();

    var w = Builder<Model.Webhook>.CreateNew().With(x => x.Id = "123").Build();

    Mock.Get(e.WebhookRepository)
        .Setup(r => r.GetById("123", default))
        .ReturnsAsync(w);

    var req = new Request
    {
        Id = "123",
        Name = "Teste",
        Description = "Webhook teste",
        Queue = "q1",
        Enabled = true
    };

    await e.HandleAsync(req, default); // <-- this is the problem

    Assert.IsTrue(e.ValidationFailed);
    Assert.IsTrue(e.ValidationFailures.Any(f => f.ErrorMessage == "A webhook with the same id already exists!"));
}
```

And the result:

```
 Message: 
Test method PrwWebhook.MinApi.Tests.Endpoints.Webhook.Manage.CreateTests.Webhook_OnExistingWithSameId_ReturnsHttp400AndErrorMessage threw exception: 
FastEndpoints.Validation.ValidationFailureException: Exception of type 'FastEndpoints.Validation.ValidationFailureException' was thrown.

  Stack Trace: 
Endpoint`2.ThrowIfAnyErrors()
Endpoint.HandleAsync(Request r, CancellationToken c) line 33
CreateTests.Webhook_OnExistingWithSameId_ReturnsHttp400AndErrorMessage() line 102
ThreadOperations.ExecuteWithAbortSafety(Action action)
```

**Comment by dj-nitehawk** [comment]
yes you're correct. if any `ThrowXXXX()` methods are used in the endpoint handler, then the exception will be thrown in a unit test.

so, i've made the `ValidationFailureException` class public in `v3.9.0-beta8`

thanks for bringing this to my attention 🙏

**Comment by fauresco** [comment]
Thank you for the great work you are doing here.

**Comment by mjbernot** [comment]
do you have an example test method to make this work?

**Comment by dj-nitehawk** [comment]
@mjbernot 
given an endpoint like this:
```cs
sealed class MyEndpoint : EndpointWithoutRequest
{
    public override void Configure()
    {
        Get("/");
        AllowAnonymous();
    }

    public override async Task HandleAsync(CancellationToken c)
    {
        await Task.CompletedTask;

        AddError("bad");
        ThrowIfAnyErrors();
    }
}
```
you can write a unit test like this:
```cs
[Fact]
public async Task Name_Of_The_Test()
{
    var ep = Factory.Create<MyEndpoint>();

    var func = async () => { await ep.HandleAsync(default); };

    var ex = await func.Should().ThrowAsync<ValidationFailureException>();

    ex.Subject.First().Failures?.Any(f => f is { PropertyName: "GeneralErrors", ErrorMessage: "bad" });
}
```
