### ISSUE TITLE
Triggering command

### ISSUE THREAD

**Issue by Zsolt-Bendes** [dj-nitehawk/FastEndpoints#5]
Hi,

I was wondering if there are other possibilities to trigger a command? For example from a background job.

Given a CRON job event (Hangfire or Quartz)
When event happened 
Then I want to trigger/invoke a (specific) command

Given a integration event (from MassTransit or CAP)
When event happened 
Then I want to trigger/invoke a (specific) command

**Comment by dj-nitehawk** [comment]
just pushed a [beta release](https://www.nuget.org/packages/FastEndpoints/2.9.0-beta3) with the ability to do so.
now you can do the following from anywhere within the app domain:
```csharp
await Event<OrderCreatedEvent>.PublishAsync(new()
{
    OrderID = "001",
    CustomerName = "customer name",
    OrderTotal = 1234.56m
});
```

**Comment by Zsolt-Bendes** [comment]
Thanks, I will give a it spin!
