### ISSUE TITLE
AddSwaggerGen and route group names not working

### ISSUE THREAD

**Issue by deltamind** [dj-nitehawk/FastEndpoints#53]
Hi @dj-nitehawk!

I trying to configure Swagger to use the routes groups names properly. But I believe I doing something wrong or there is some kind of error.
This is how my route is shown:
![image](https://user-images.githubusercontent.com/16664966/156878193-3f4db3c3-bf5b-4e79-94cd-7508133adbcc.png)

No matter what why try, I cannot change this group name (in this case I just want to make first letter uppercase, as "Login").
I tryied to use the WithTags method, but the route appears duplicated:
![image](https://user-images.githubusercontent.com/16664966/156878399-03986b19-1971-464d-8b55-ee7ca262563f.png)
![image](https://user-images.githubusercontent.com/16664966/156878428-ff71c794-3cda-402a-8086-10aaa08e9bb4.png)

I´m not sure but I think there is some kind of bug on this.

And in my research for a solution, I realized the AddSwaggerGen method is not working. I putted a breakpoint on it and never stopped there. Is there something about this method not work with FastEndpoints and minimal APIs?

Regards!

**Comment by dj-nitehawk** [comment]
here's how you do it:
```csharp
global using FastEndpoints;
using FastEndpoints.Swagger; //add this

var builder = WebApplication.CreateBuilder();
builder.Services.AddFastEndpoints();
builder.Services.AddSwaggerDoc(tagIndex: 0); //add this

var app = builder.Build();
app.UseAuthorization();
app.UseFastEndpoints();
app.UseOpenApi(); //add this
app.UseSwaggerUi3(s => s.ConfigureDefaults()); //add this
app.Run();

public class LoginEndpoint : Endpoint<EmptyRequest, EmptyResponse>
{
    public override void Configure()
    {
        Get("/login");
        AllowAnonymous();
        Options(x => x.WithTags("Login"));
    }

    public override Task HandleAsync(EmptyRequest req, CancellationToken ct)
    {
        return SendOkAsync();
    }
}
```
gotta set the `tagIndex: 0` to disable the auto tagging based on url segment and specify the tag you want via `WithTags()`. also don't use `AddSwaggerGen()`. the correct one is `AddSwaggerDoc()`

**Comment by deltamind** [comment]
Worked like a charm:
![image](https://user-images.githubusercontent.com/16664966/156879342-e77c45ba-ebfc-490b-88cb-84bff3d0ae5e.png)
Tks for super quick answer!
