### ISSUE TITLE
Referencing FluentValidation library vs. integrating it in the next major release

### ISSUE THREAD

**Issue by msmolka** [dj-nitehawk/FastEndpoints#54]
I'd like to ask, why fluent validation is implemented inside code and not by referencing external package?
It causes some separation issues with FluentValidation together with implicit usings. There are using conflicts.

**Comment by dj-nitehawk** [comment]
why have you installed FluentValidation package in your project? you don't need to.

**Comment by msmolka** [comment]
I have older project that I would like to migrate. And my question is still valid. Any custom extensions written for fluent validation won't work.

**Comment by dj-nitehawk** [comment]
yeah i don't remember exactly why i went with this approach. but there's some modifications done to the FV code base to better integrate it with fastendpoints. i guess you'll have to update your custom extensions to use the `FastEndpoints.Validation` namespace and uninstall original package from the project. just do a text find and replace and you'll be alright.

**Comment by Allann** [comment]
I was wondering the same thing.  And the question still hasn't been answered.  I forked the code just so I could remove it, I can't see any benefit to copying the code local.

**Comment by dj-nitehawk** [comment]
i'm not gonna answer it as i can't remember what exactly i changed in the FV code except for some language stuff and namespaces. soooo... i'm afraid we will have to live with what we got until the next major version cause we have many projects in production which will be broken if changed now. sorry about the inconveniece :-)

**Comment by dj-nitehawk** [comment]
if any other's seeing this think we should switch to just referencing fluentvalidation library instead of integrating it, please cast your vote here to make a breaking change at version 4.0.

obviously the downside would be your existing projects would have to do a wholesale text find/replace and some manual fixing up cause the fluentvalidations code lives in multiple namespaces.

**Comment by stefandevo** [comment]
Agree that it shouldn't be copy/pasted in the library if it's only for the namespaces. I would even prefer to have Validation abstracted anyway (like the JSON serializer already is); so better to have interfaces for it, and then implement it using the FluentValidation as an external library. Then you can always choose to use or not use it.

**Comment by dj-nitehawk** [comment]
@stefandevo i don't think i'll have the time to look into it for the next couple of weeks. if you have some time, have a crack at it and send in a PR. 

we could ship it in v4.0 if there's gonna be some major breaking changes. hopefully, the damage can be minimized. commit your changes to the `vNext` branch if you decide to work on it.

if you open a draft PR, i'll follow along what you're doing.

most importantly, the current performance should not be degraded. run the [benchmarks project](https://github.com/dj-nitehawk/FastEndpoints/tree/main/Benchmark/Runner) to check if there's any regression.

**Comment by Allann** [comment]
if noone else does, i'll give it a crack on the weekend.

**Comment by ColinM9991** [comment]
I also agree it shouldn't be part of the solution as it constrains users to what ever version is currently in place. It also places an additional burden on contributors to keep it up to date and merge any custom code.

**Comment by dj-nitehawk** [comment]
so we're going for a breaking change in v4.0
thanks @hoppel for the PR #70
