### ISSUE TITLE
Redirect to url

### ISSUE THREAD

**Issue by NepCono** [dj-nitehawk/FastEndpoints#55]
Maybe stupid question but how do I do a Response Redirect to another url.
When I try with postman the location is set to the url but it is not executed.

**Comment by dj-nitehawk** [comment]
```csharp
public class MyEndpoint : Endpoint<EmptyRequest>
{
    public override void Configure()
    {
        Get("/test-redirect");
        AllowAnonymous();
    }

    public override async Task HandleAsync(EmptyRequest req, CancellationToken ct)
    {
        await SendRedirectAsync("https://google.com", isPermanant: true);
    }
}
```

the `SendRedirectAsync` method was added in `v3.10.0-beta2`. so you'll have to upgrade to the beta until the final v3.10 is released. which would need a few more days of testing. but it's quite stable for production use.

**Comment by NepCono** [comment]
Thank you 👍
