### ISSUE TITLE
Support C# Records for Request/Response DTOs

### ISSUE THREAD

**Issue by Zsolt-Bendes** [dj-nitehawk/FastEndpoints#6]
Is it possible to allow `record`s for request and response types? Currently it is restricted to `class` only.

Also, adding source generator config for request and responses in the VS extension would improve performance. Just and idea.

Example:
```
using System.Text.Json.Serialization;

namespace SomeNameSpace;

[JsonSerlializable(typeof([SomeRequestName]))]
public partial class [SomeRequestName]JsonContext : JsonSerializerContext
{
}
```
[Some info about json source generator](https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-source-generator/)
(I don't know if source generator works with `record` types.)

**Comment by dj-nitehawk** [comment]
records for request dtos is currently not possible because model binding is done in [multiple stages](https://github.com/dj-nitehawk/FastEndpoints/blob/ab0aaee046b0644098246ac6ea1596f38c872614/Src/Library/Endpoint.Static.cs#L17) and the dtos have to be mutable to do that.

i looked through the aspnet source code to see how they achieve it and i think i just gave myself a brain aneurysm 🥴

so, we're gonna need some help from the community to support c# records. if anybody seeing this is willing to give it a go, please submit a PR.

---

as for source generator support, i'll look in to it soon...

**Comment by Zsolt-Bendes** [comment]
Well if supporting `record` type is to much effort for small value don't bother with it. I thought it would be a nice improvement. 
The source generator should be do able, but only makes sense for request if some one is sending a json in the body.

**Comment by dj-nitehawk** [comment]
well it looks like source gen can already be used quite easily like so:
**startup:**
```csharp
builder.Services.Configure<JsonOptions>(o =>
{
    o.SerializerOptions.PropertyNamingPolicy = null;
    o.SerializerOptions.AddContext<SerializerContext>();
});
```
**json serializer context:**
```csharp
[
    JsonSerializable(typeof(Admin.Login.Request)),
    JsonSerializable(typeof(Admin.Login.Response)),
    JsonSerializable(typeof(Customers.Create.Request)),
    JsonSerializable(typeof(Customers.List.Recent.Response))
]
public partial class SerializerContext : JsonSerializerContext { }
```
[here's a working sample](https://github.com/dj-nitehawk/FastEndpoints/blob/ff3b084c531b9388efc5a94a56b4138fb34a0dc6/Web/Program.cs#L20)

now if we can figure out how to define the serializer context dynamically by the library avoiding the need for the user to define like live above, it would be bloody marvelous...

**Comment by Zsolt-Bendes** [comment]
I have a brain fart idea for that. A build source generator could scan the code and look for all the queries and responses and create the setup for the actual serializer. 

I never implemented a source generator before. I appreciate that you invest so much time into this library.

**Comment by dj-nitehawk** [comment]
thanks!
and yeah that could actually work.
let me investigate that...

**Comment by dj-nitehawk** [comment]
@Zsolt-Bendes tried your idea but it didn't work. 

i managed to generate a serializer context with code-gen but the json code generator doesn't pick up my generated class :-(
i'll leave this aside as i feel code generation isn't still there yet to provide a good consumer experience.

also multiple `JsonSerializable` attributes on a single context only generates for the first attribute and ignores the rest. so the above code with multiple attributes on a single context doesn't seem to work.

multiple `o.SerializerOptions.AddContext` calls also fails.

as of now, whatever minor performance improvements we can get with codegen, will greatly outweigh the effort we have to put in to get it to work.

let's see what the future brings...
