### ISSUE TITLE
Integration test does not serialise my request

### ISSUE THREAD

**Issue by stefandevo** [dj-nitehawk/FastEndpoints#61]
I can't pinpoint why my integration test is not working; it seems somewhere the request object doesn't get serialised into my Endpoint method.

I hope you can give me some clues where to find the issue.

I am using a middleware just to see whether the json object is posted. That is the case.
But in the end the HandleAsync(Request req, CancellationToken ct) req object stays empty.

I am using XUNIT. 

Using this class definition `public class EndpointFixture : WebApplicationFactory<Program>` to get my unit testing to work.

The unit test class itself
`public class EndpointTests : IClassFixture<EndpointFixture>`

```
	[Fact]
	public void LoginForUnknownUser()
	{
		var client = _fixture.GetAnonymousClient("en");
		var (_, result) = client
			.POSTAsync<Endpoint, Request, Response>(
				new Request
				{
					Email = "unknown@user.com"
				}).GetAwaiter().GetResult();

	// leaving out my assertions here
	}
```

the GetAnonymousClient is coming from the EndpointFixture class

```
public HttpClient GetAnonymousClient(string language)
	{
		var client = Server.CreateClient();
		client.DefaultRequestHeaders.Add("X-Request", "XXXXXXX");
		client.DefaultRequestHeaders.Add("X-Language", language);
		return client;
	}
```

As said, when I place break points, my Endpoint is called OK (so the client basically is working, and using my discovered endpoints)

By my request object - the properties of it - are all null while I know 100% sure (my debugging my Middleware) that I get the correct json with the Email field filled-in.

Can you point me in a direction / hook where I can see when the request object is filled so I can debug through it?

Debug print of the response body:
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/1656051/157913401-b74bb0d1-4ca6-40f5-a425-eb357e69e237.png">

Same call, outside the unit test:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/1656051/157913836-2b6a3cf0-68f3-4006-8301-1046e31a92b4.png">

where my request is filled in.

```
public class Request
{
	public string Email { get; set; }
}
```

**Comment by dj-nitehawk** [comment]
in bed right now so will have a look at this tomorrow morning. in the meantime if you reference the FastEndpoints source and add a breakpoint at the following location and then step through, you might be able to find out what's happening. 

https://github.com/dj-nitehawk/FastEndpoints/blob/f5fdbe5beac4e4a897c080c23c8def6176317e9f/Src/Library/Endpoint/Endpoint.Static.cs#L12

**Comment by stefandevo** [comment]
OK; it's sure a serialisation issue.

<img width="1528" alt="image" src="https://user-images.githubusercontent.com/1656051/157915346-615fcea4-6cd5-453a-8ad4-8be459005bc5.png">

even reading the body from within the handler, I see the correct json;

Will try to investigate further.

**Comment by dj-nitehawk** [comment]
deserialization of the request dto only fails in the integration test right? works correctly from a browser or postman or something?

**Comment by stefandevo** [comment]
Yes correct. Only during test

**Comment by stefandevo** [comment]
FYI
I tried to debug, and came up with following issue:

```
    private static async Task<TRequest> BindToModel(HttpContext ctx, List<ValidationFailure> failures, JsonSerializerContext? serializerCtx, CancellationToken cancellation)
    {
        TRequest? req = default;

        if (ctx.Request.ContentLength > 0)
```

The `ctx.Request.ContentLength` is where it goes wrong. The `ContentLength` is 0 during the integration test; however, if I skip the `if` statement and move on to the next block

```
            if (isPlainTextRequest)
                req = await BindPlainTextBody(ctx.Request.Body).ConfigureAwait(false);
            else if (ctx.Request.HasJsonContentType())
                req = (TRequest?)await FastEndpoints.Config.ReqDeserializerFunc(ctx.Request, tRequest, serializerCtx, cancellation);
```

everything works fine; for some reason the `ContentLength` check is "different" when running from regular http client.

**Comment by stefandevo** [comment]
https://github.com/dotnet/aspnetcore/issues/18463
related?

**Comment by dj-nitehawk** [comment]
interesting indeed. all the [integration tests here](https://github.com/dj-nitehawk/FastEndpoints/tree/main/Test) are using the same approach with MSTest and the content length property is properly set automatically.

maybe its a issue with xunit + waf?

could you give it a shot with mstest?

ideally all clients should automatically set the content-length header if there is some content in the body.

**Comment by stefandevo** [comment]
Would love to keep using XUnit
What about this remark:
https://docs.microsoft.com/en-us/aspnet/core/test/middleware?view=aspnetcore-6.0#content-length-and-transfer-encoding-headers


**TestServer does not set transport related request or response headers such as [Content-Length](https://developer.mozilla.org/docs/Web/HTTP/Headers/Content-Length) or [Transfer-Encoding](https://developer.mozilla.org/docs/Web/HTTP/Headers/Transfer-Encoding). Applications should avoid depending on these headers because their usage varies by client, scenario, and protocol.**

**Comment by stefandevo** [comment]
Temporary fix for me; in my (already) running middleware, I am setting the ContentLength myself if running from a unit-test. Then it works.
Still think you might reconsider that `if (ctx.Request.ContentLength > 0)` check.

**Comment by stefandevo** [comment]
As far as I can see, there is no need to have the check there; all calls behind it don't have an issue with the ContentLength property 0 but the underlying stream contains data.

**Comment by dj-nitehawk** [comment]
yeah making the change now... will push out next beta in a few minutes!
this check was an old relic from some past code which is no longer necessary...

**Comment by dj-nitehawk** [comment]
`v3.11.0-beta3` released
