### ISSUE TITLE
Roles produces CORS error when not authorized using Cookie Authentication & MicrosoftIdentityWebApp

### ISSUE THREAD

**Issue by EelcoLos** [dj-nitehawk/FastEndpoints#63]
## Expected Behavior
When not having a `Roles` role in cookie authentication, I expect a 401 error to be returned

## Actual Behavior
![image](https://user-images.githubusercontent.com/5102501/158331404-c00a9894-a98a-41e6-9a2b-7be77c4f28eb.png)
We receive a CORS error

## Steps to Reproduce the Problem

  1. Have cookie authentication up and running in a .net 6 application
  1. write an EndPoint, eg:
  ```csharp
public class DeleteProjectEndpoint : Endpoint<DeleteProjectsEndpointRequest>
{
	public override void Configure()
	{
		Verbs(Http.DELETE);
		Routes("/projects/{ProjectId}/models/{ModelId}");
		Options(x =>
		{
			x.WithName("deleteProject");
			x.ProducesValidationProblem();
		});
		//todo fix should return 401/403
		Roles("Admin");
	}

	public async override Task HandleAsync(DeleteProjectsEndpointRequest req, CancellationToken ct)
	{
		var command = new DeleteProjectCommand
		{
			ProjectId = req.ProjectId,
			ModelId = req.ModelId,
		};

		var handler = TryResolve<DeleteProjectCommandHandler>();
		if (handler == null)
		{
			ThrowError("Handler not resolved");
			return;
		}

		var (succeeded, validationResults) = await handler.HandleAsync(command);

		if (!succeeded)
		{
			ThrowError("Delete project not succeeded");
			return;
		}

		foreach (var error in validationResults.Errors) AddError(error.ErrorMessage);

		ThrowIfAnyErrors();

		await SendNoContentAsync(ct);
	}
}
```

## Specifications

  - Version: 3.10
  - Platform: Windows

**Comment by EelcoLos** [comment]
As discussed on Discord, we're noticing this issue being the problem of MicrosoftIdentityWebApp.
At the moment we're investigating if this middleware is adding items to the `AuthorizeAttributes`.

**Comment by EelcoLos** [comment]
After intensive research, we finally reached a conclusion, with perhaps some discussion:
When `MicrosoftIdentityWebApp` notices an Access Denied (Via the [AuthorizationMiddelware](https://github.com/dotnet/aspnetcore/blob/c85baf8db0c72ae8e68643029d514b2e737c9fae/src/Security/Authorization/Policy/src/AuthorizationMiddleware.cs) ) it triggers on the `policyEvaluator` to all Evaluators.
On `MicrosoftIdentityWebApp`, you can set the various events, ie using `OpenIdConnectEvents`, such as: `OnAccessDenied`, `OnMessageReceived`, `RedirectToIdentityProvider`, etc.
For some reason `MicrosoftIdentityWebApp` decides that an AccessDenied by default should trigger the `RedirectToIdentityProvider` event. You _can_ interrupt this event by triggering your own statuscode and using `context.Response.CompleteAsync()` to terminate all subsequent calls.
To us, this seemed wrong.
So we were looking for another approach:
We wrote a piece of middleware that makes any Request **not** trigger the 302 Redirect, because of a header setting called `X-Requested-With` with the value `XMLHttpRequest`.
```csharp
app.Use(async (context, next) =>
{
	if (context.Request.Path.HasValue && context.Request.Path.Value.StartsWith("/api"))
		context.Request.Headers.Add("x-requested-with", "XMLHttpRequest");
	await next();
});
```
We noticed setting this as Middleware _before_ any authentication, this header will make sure anything else will not make a redirect anyway.

Although this implicates any subsequent errors, our testing shows the location header still being filled with MicrosoftIdentityWebApp/AccessDenied, it also properly shows the 403 forbidden statuscode. This was primarily what we were looking for

**Comment by dj-nitehawk** [comment]
i'm sure this info will come in handy for others using `MicrosoftIdentityWebApp`. good work mate!
so i will go ahead and close this issue. feel free to re-open in case you need to discuss again.
