### ISSUE TITLE
How to throw error/exception from another class library

### ISSUE THREAD

**Issue by shashikantpawar21** [dj-nitehawk/FastEndpoints#64]
Can anyone help with sample code where exception are handled globally at one place with FastEndpoints

**Comment by dj-nitehawk** [comment]
what is your requirement?

to globally handle uncaught exceptions or to customize the error response serialization?

there's a built-in global exception handler you can use as mentioned [here](https://fast-endpoints.com/wiki/Exception-Handler.html).

alternatively you can write your own global exception handler by following the [source code](https://github.com/dj-nitehawk/FastEndpoints/blob/main/Src/Library/Extensions/ExceptionHandlerExtensions.cs) of the built-in handler.

or if the need is to customize the error response, have a look [here](https://fast-endpoints.com/wiki/Configuration-Settings.html#customizing-error-responses).
