### ISSUE TITLE
The `Endpoint.SerializerContext<TContext>()` option should have an overload that accepts a specific instance of `JsonSerializerContext` so the generated code can be used for serialization

### ISSUE THREAD

**Issue by CoryCharlton** [dj-nitehawk/FastEndpoints#67]
The generated serialization code in a `JsonSerializationContext` will only be used if the supplied `JsonSerializerOptions` are [compatible](https://github.com/dotnet/runtime/blob/a1bf79e06b64edef0957a9cc907180c25fa8aab9/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerContext.cs#L42). 

If the options are not compatible then `JsonSerializer` will [fallback](https://github.com/dotnet/runtime/blob/8b4eaf94140f488743d0c78caa3afec3b9c5d789/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Write.Helpers.cs#L38) to the standard serialization logic which mean we get no benefit from the `JsonSerializationContext`.

Since even the default options supplied in `Microsoft.AspNetCore.Http.Json.JsonOptions` as not compatible with the generated serialization code the majority of use cases for `Endpoint.SerializerContext<TContext>()` will be pointless.

Here's a benchmark that compares the default context against a context created using the default options supplied in `Microsoft.AspNetCore.Http.Json.JsonOptions`

### Results

|                                  Method |     Mean |    Error |   StdDev | Ratio | RatioSD |  Gen 0 | Allocated |
|---------------------------------------- |---------:|---------:|---------:|------:|--------:|-------:|----------:|
|                          JsonSerializer | 976.1 ns | 16.59 ns | 21.57 ns |  1.00 |    0.00 | 0.2346 |     984 B |
| JsonSerializerContext_Generated_Options | 581.6 ns | 11.49 ns | 20.72 ns |  0.60 |    0.02 | 0.1526 |     640 B |
|    JsonSerializerContext_Custom_Options | 975.2 ns | 11.52 ns | 10.21 ns |  1.00 |    0.03 | 0.2346 |     984 B |
|          JsonTypeInfo_Generated_Options | 495.1 ns |  9.04 ns | 12.37 ns |  0.51 |    0.02 | 0.1526 |     640 B |
|             JsonTypeInfo_Custom_Options | 961.2 ns | 13.39 ns | 12.53 ns |  0.98 |    0.02 | 0.2346 |     984 B |

### Setup

```csharp
private static readonly EndpointSerializerContext _customContext = new(new Microsoft.AspNetCore.Http.Json.JsonOptions().SerializerOptions);
private static readonly EndpointSerializerContext _generatedContext = EndpointSerializerContext.Default;
```

### Benchmarks

```csharp
[Benchmark(Baseline = true)]
public void JsonSerializer() =>
    System.Text.Json.JsonSerializer.Serialize(_response, _response.GetType(), JsonSerialization.SerializerOptions);

[Benchmark]
public void JsonSerializerContext_Generated_Options() =>
    System.Text.Json.JsonSerializer.Serialize(_response, _response.GetType(), _generatedContext);

[Benchmark]
public void JsonSerializerContext_Custom_Options() => 
    System.Text.Json.JsonSerializer.Serialize(_response, _response.GetType(), _customContext);

[Benchmark]
public void JsonTypeInfo_Generated_Options() =>
    System.Text.Json.JsonSerializer.Serialize(_response, _generatedContext.SitesResponse);

[Benchmark]
public void JsonTypeInfo_Custom_Options() =>
    System.Text.Json.JsonSerializer.Serialize(_response, _customContext.SitesResponse);
```

I'll submit a PR with a proposed fix.

**Comment by dj-nitehawk** [comment]
`v4.0.0-beta1` is on nuget. pls give it a try.
thanks for the PR 🙏
