### ISSUE TITLE
Getting typeloader exception

### ISSUE THREAD

**Issue by murunwas** [dj-nitehawk/FastEndpoints#7]
I created new project and follow all the `getting started guide`, When I run the project, I'm getting exception shown below :

![image](https://user-images.githubusercontent.com/8838943/141006762-e3e67f2e-1af6-4748-89ce-33559a7ea16e.png)

**Comment by dj-nitehawk** [comment]
you probably don't have .net 6.0 sdk installed which is required.
[see here](https://streamable.com/yzio6z) it works without issue when you have the correct sdk version installed.

if you do have the final version of the .net 6.0 sdk, can you check with a regular minimal api new project? does that run correctly on your system?

**Comment by murunwas** [comment]
@dj-nitehawk  I was using .net 6 RC then updated to .net 6 LTS and it's working fine, thanks 💯
