### ISSUE TITLE
GlobalEndpointOptions CORS Problem

### ISSUE THREAD

**Issue by zhixXiang** [dj-nitehawk/FastEndpoints#75]
Hi sir,
can I set RequireCors(x => x.AllowAnyOrigin()) in the program.cs ?
I add but produce error:
"Endpoint HTTP: POST /api/Login contains CORS metadata, but a middleware was not found that supports CORS.\r\nConfigure your application startup by adding app.UseCors() in the application startup code. If there are calls to app.UseRouting() and app.UseFastEndpoints(), the call to app.UseCors() must go between them.

```
app.UseFastEndpoints(c =>
{
    c.RoutingOptions = o => o.Prefix = "api"; // url prefix

    c.SerializerOptions = o =>
    {
        o.PropertyNamingPolicy = null; // set null for pascal case
    };
    c.GlobalEndpointOptions = (endpoint, builder) =>
    {
        builder.RequireCors(x => x.AllowAnyOrigin()) // add this produce error
               .RequireHost("localhost")
               .ProducesProblem(StatusCodes.Status403Forbidden);
    };
});
```

**Comment by dj-nitehawk** [comment]
like the error says you need to have the cors middleware in the pipeline like in the following example: 

https://github.com/dj-nitehawk/FastEndpoints/blob/5316ae81a18b67ad992afa66761757c37927c237/Web/Program.cs#L12

**Comment by zhixXiang** [comment]
Thank you!
