### ISSUE TITLE
Uploading large files to Blob Storage with streaming

### ISSUE THREAD

**Issue by Mithgroth** [dj-nitehawk/FastEndpoints#79]
I see that we can upload and handle files as an `IFormFile`, however in my case, I'd like to handle very large video file uploads.

I'm following the [official docs](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-5.0#upload-large-files-with-streaming), along with [advices from Rachel Hagerman](https://trailheadtechnology.com/dos-and-donts-for-streaming-file-uploads-to-azure-blob-storage-with-net-mvc/).

> If you let MVC try to bind to an IFormFile, it will attempt to spool the entire file into memory. Which is exactly what we don’t want to do with large files.

She mentions to avoid `IFormFile`, model binding and also `MemoryStream` altogether; and in fact she makes perfect sense as you'd be draining the server's memory, causing a lot of trouble.

I was wondering if there is a way to approach this with FastEndpoints.

**Comment by dj-nitehawk** [comment]
you can now do the following with `v4.1.0-beta1`
```csharp
global using FastEndpoints;

var builder = WebApplication.CreateBuilder();
builder.WebHost.ConfigureKestrel(o =>
{
    o.Limits.MaxRequestBodySize = 5368709120; //set max request body size to 5gb
});
builder.Services.AddFastEndpoints();

var app = builder.Build();
app.UseAuthorization();
app.UseFastEndpoints();
app.Run();

public class Upload : EndpointWithoutRequest
{
    public override void Configure()
    {
        Post("upload-file");
        AllowAnonymous();
        AllowFileUploads(dontAutoBindFormData: true); //this allows streaming of large files without buffering to memory/disk
    }

    public override async Task HandleAsync(CancellationToken ct)
    {
        await foreach (var section in FormFileSectionsAsync(ct))
        {
            if (section is not null)
            {
                using (var fs = System.IO.File.Create(section.FileName))
                {
                    await section.Section.Body.CopyToAsync(fs, 1024 * 64, ct);
                }
            }
        }

        await SendOkAsync("upload complete!");
    }
}
```
