### ISSUE TITLE
How to read claim values + handling multiple http verbs

### ISSUE THREAD

**Issue by JigarPrajpati** [dj-nitehawk/FastEndpoints#8]
Hi, i'm so happy to see your fastendpoints and started to use it, and still not reach at there where i can find two things. please let me know do you have following features so i can work easily.

1. I mostly use User.Identity.Name to access ID of current logged in user, because this is only the shortcut variable to access userId, but i can see your fastend point support string[] array for claims, so due to continuously required userID, i must need something like **User.Identity.Name** to access claim userId. i don't want to access all the userId by `Claim.Where(x=>x.Type=="ClaimName").FirstOrDefault().value`.

So help me on this please.

2. I seen for single endpoint a whole class need to be create, instead of in single class where CRUD operation i can do like MVCController. so do you have any features like in singleClass of Endpoint i can add GET,POST,PUT,PATCH verbs insted of create new class for each verbs?

**Comment by dj-nitehawk** [comment]
i think the following example will answer all of your questions. as you can see, a single endpoint can handle multiple http verbs. however the philosophy with this library is, there is always only 1 handler method per single endpoint/route/feature. here's an [example](https://github.com/dj-nitehawk/MongoWebApiStarter/tree/master/Template/Source/%5BFeatures%5D) of how i usually structure my projects.
```csharp
public static class Claim
{
    public const string UserName = "Name";
    public const string UserID = "UserID";
    public const string UserType = "UserType";
}

public class Request
{
    [From(Claim.UserName, IsRequired = false)] //set IsRequired to true if user must posses the claim
    public string UserName { get; set; } //auto binds value from current user principal
}

public class Response
{
    public string UserID { get; set; }
    public string UserName { get; set; }
    public string UserType { get; set; }
}

public class UserEndpoint : Endpoint<Request, Response>
{
    public override void Configure()
    {
        Routes("/api/user"); //define route for this endpoint

        Verbs(
            Http.GET,
            Http.POST,
            Http.DELETE); //handle multiple http verbs for a single endpoint

        AllowAnonymous(Http.POST); //this allows unauthenticated user to send POST request
    }

    public override async Task HandleAsync(Request r, CancellationToken c)
    {
        if (User.Identity?.IsAuthenticated is false && HttpMethod == Http.POST)
        {
            //create a new user here

            Response.UserID = "001";
            Response.UserName = r.UserName;
            Response.UserType = "Member";
            await SendAsync(Response); //or you can do SendAsync(new Response {...})
            return;
        }

        var userName = User.Identity?.Name; //read from identity or...
        var userNameClaimVal = r.UserName; //read auto bound val from request dto

        if (HttpMethod == Http.GET)
        {
            //find user from db...
        }

        if (HttpMethod == Http.DELETE)
        {
            //delete user from db...
        }

        await SendAsync(Response);
    }
}
```

**Comment by dj-nitehawk** [comment]
check out this article too when you have some time: https://ardalis.com/mvc-controllers-are-dinosaurs-embrace-api-endpoints/

**Comment by JigarPrajpati** [comment]
Thanks, it works fine, but there is one another concern that we have one class called Employee now employee having AllEmployee, SingleEmplyee, SpecialEmployee API so how can i make bunch of API in single FastEndpoint class?

**Comment by dj-nitehawk** [comment]
the design principal of [REPR pattern](https://deviq.com/design-patterns/repr-design-pattern) dictates that there should only be one handler per endpoint in order to prevent endpoint bloating that typically happens with mvc controllers.

what you are asking is typically handled like the following in REPR pattern together with Vertical Slice Architecture. i.e. you should have deeply nested folder structures with 1 folder per feature slice which is a single endpoint. you need to let go of your mvc mentality to progress with this pattern. trust me it will pay off big time in the future when you need to evolve your applications.

![screen](https://user-images.githubusercontent.com/7043768/145162721-dc45a39c-bd6f-4112-a4bc-b30225ac43ca.png)

**Comment by jigarprajapatieastern** [comment]
I'm sorry to understand it, but let me know in short word. normally we are having one controller and multiple methods, so does it support in your fastendpoint library. like create one endpoint class and support multiple method like GetEmployee, GetStudents, PostResult etc..?

**Comment by dj-nitehawk** [comment]
no you need to create a separate endpoint per request. 

one request -> one handler -> one response

GetEmployeeEndpoint.cs 
GetStudentsEndpoint.cs 
PostResultEndpoint.cs 

so you create 3 separate endpoint classes to handle 3  different requests to the system.
