### ISSUE TITLE
ability to model bind multiple values to non-scalar properties from query parameters

### ISSUE THREAD

**Issue by EthemAcar-Dev** [dj-nitehawk/FastEndpoints#82]
PersonRequest.cs:

public int[]? Ids { get; set; } = null;

Swagger Call:
http://localhost:3000/api/person?ids=5&ids=15

Result:
PersonRequest.Ids is null.

Expected array of ints with 5 and 15 as items.

**Comment by dj-nitehawk** [comment]
as mentioned in the [docs](https://fast-endpoints.com/wiki/Model-Binding.html#form-fieldsroutequeryclaimsheaders), only scalar values can be bound from query parameters atm. multiple value binding is in the todo list.

in the meantime you could access the query items like so:
```csharp
public override Task HandleAsync(CancellationToken ct)
{
    var ids = HttpContext.Request.Query["ids"]
        .Select(i=> int.Parse(i));

    return SendAsync(ids);
}
```
or send the array in the request body.

if someone would like to contribute this feature, please submit a PR.

**Comment by dj-nitehawk** [comment]
@nefarius yeah i also don't really like the idea of multiple query params with the same name. it's just a bad design inherited from mvc. that's why i'm not too keen to work on this feature myself before knocking out more important stuff on the todo list ;-)

**Comment by EthemAcar-Dev** [comment]
> Isn't `ids=5&ids=15` a quite unusual approach to specify a range? Looks to me as you're setting/overwriting the same value again in one query. Wouldn't `ids=5,15` or `ids=[5,15]` or similar make more sense?

It's what swagger does. To me it looks ridiculous 😅

**Comment by hoppel** [comment]
Havent seen query parameters used like this in a while 😛.  The "manual" solution is probably good enough for now tbh

**Comment by fretje** [comment]
> Isn't `ids=5&ids=15` a quite unusual approach to specify a range? Looks to me as you're setting/overwriting the same value again in one query. Wouldn't `ids=5,15` or `ids=[5,15]` or similar make more sense?

> @nefarius yeah i also don't really like the idea of multiple query params with the same name. it's just a bad design inherited from mvc. that's why i'm not too keen to work on this feature myself before knocking out more important stuff on the todo list ;-)

I thought using the same name for multiple query params is actually what has been done since the beginning of web forms. When you have a select which allows to select multiple values, the values are sent like that... might be a bad design (definitely not mvc's as it predates that significantly)... but at least everything on the internet (should) understand and be able to parse that...
