### ISSUE TITLE
How to use Api_Key instead of JWT

### ISSUE THREAD

**Issue by EthemAcar-Dev** [dj-nitehawk/FastEndpoints#83]
I'm trying to use Api_Key which is specified in header. My swagger settings are great i followed the documentation of FastEndpoints. What confuses me is the authentication part. It keeps saying I'm not authorized. I just want the user to use the API key to authenticate there is no login endpoint in my security.

My code:

```
var builder = WebApplication.CreateBuilder(args);

builder.Services.AddFastEndpoints();

builder.Services
    .AddSwaggerDoc(s =>
    {
        s.DocumentName = "Initial Release";
        s.Title = "My API";
        s.Version = "v1.0";
        s.AddAuth("ApiKey", new()
        {
            Type = OpenApiSecuritySchemeType.ApiKey,
            Name = "api_key",
            In = OpenApiSecurityApiKeyLocation.Header,
            Description = "Fill in your Api Key"
        });
    }, addJWTBearerAuth: false);

var app = builder.Build();
app.UseAuthorization();
app.UseFastEndpoints();

app.UseOpenApi();

app.UseSwaggerUi3(c => c.ConfigureDefaults());

app.Run("http://localhost:3000");
```

Exception i receive:
`System.InvalidOperationException: No service for type 'Microsoft.AspNetCore.Authentication.IAuthenticationService' has been registered.`

Even when i add app.UseAuthentication(); its not working.

What am i doing wrong?

**Comment by dj-nitehawk** [comment]
since asp.net doesn't have a built-in api key middleware, you need to write your own like the following:
```csharp
global using FastEndpoints;
using FastEndpoints.Swagger;
using NSwag;

var builder = WebApplication.CreateBuilder();
builder.Services.AddFastEndpoints();
builder.Services.AddAuthentication();
builder.Services.AddSwaggerDoc(s =>
{
    s.AddAuth("ApiKey", new()
    {
        Name = "api_key",
        In = OpenApiSecurityApiKeyLocation.Header,
        Type = OpenApiSecuritySchemeType.ApiKey,
    });
}, addJWTBearerAuth: false);

var app = builder.Build();
app.UseMiddleware<ApiKeyMiddleware>();
app.UseAuthorization();
app.UseFastEndpoints();
app.UseOpenApi();
app.UseSwaggerUi3(s => s.ConfigureDefaults());
app.Run();

public class ApiKeyMiddleware
{
    private const string APIKEYNAME = "api_key";
    private readonly RequestDelegate _next;

    public ApiKeyMiddleware(RequestDelegate next)
    {
        _next = next;
    }

    public async Task InvokeAsync(HttpContext context)
    {
        if (context.Request.Path.Value?.Contains("/swagger") is true)
        {
            await _next(context);
            return;
        }

        if (!context.Request.Headers.TryGetValue(APIKEYNAME, out var extractedApiKey))
        {
            context.Response.StatusCode = 401;
            await context.Response.WriteAsync("Api Key was not provided. (Using ApiKeyMiddleware)");
            return;
        }

        var appSettings = context.RequestServices.GetRequiredService<IConfiguration>();
        var apiKey = appSettings.GetValue<string>(APIKEYNAME) ?? "test-key";

        if (!apiKey.Equals(extractedApiKey))
        {
            context.Response.StatusCode = 401;
            await context.Response.WriteAsync("Unauthorized client. (Using ApiKeyMiddleware)");
            return;
        }

        await _next(context);
    }
}

public class Test : EndpointWithoutRequest
{
    public override void Configure()
    {
        Get("test");
        AllowAnonymous();
    }

    public override async Task HandleAsync(CancellationToken ct)
    {
        await SendAsync("you are authorized!");
    }
}
```

**Comment by nefarius** [comment]
`AllowAnonymous();` deliberately suppresses the need for authentication/authorization so it behaves as expected?

**Comment by EthemAcar-Dev** [comment]
Updated code works perfect, my suggestion is to add this to the documentation too. Thanks for help <3

**Comment by dj-nitehawk** [comment]
updated the demo code with a better approach using a custom authentication handler

**Comment by MutedExclamation** [comment]
There's one thing I don't understand, though. Since `.UseSwaggerGen()` is used _after_ calling `.UseAuthorization()` it means the `/swagger` web page needs authentication too. So, the only way to access the docs is to manually edit the API key header. Can you make the swagger document accessible anonymously?

**Comment by EthemAcar-Dev** [comment]
> There's one thing I don't understand, though. Since `.UseSwaggerGen()` is used _after_ calling `.UseAuthorization()` it means the `/swagger` web page needs authentication too. So, the only way to access the docs is to manually edit the API key header. Can you make the swagger document accessible anonymously?

Swagger is anonymously accessible with the provided demo code.

**Comment by MutedExclamation** [comment]
> Swagger is anonymously accessible with the provided demo code.

Not if you use a fallback authorization policy (as you, arguably, should).
You have to add the `AllowAnonymous` attribute to unprotected endpoints _or_ register the Swagger middleware before the auth middleware. Both of these solutions are unavailable now.

**Comment by edmolko** [comment]
I'm having the same issue. Currently, I have this guard on my custom handler:

```
 protected override Task<AuthenticateResult> HandleAuthenticateAsync()
 {
     if (RequestIsFromSwaggerUI())
         return Task.FromResult(AuthenticateResult.Success(new AuthenticationTicket(new ClaimsPrincipal(), Scheme.Name)));
         
        //ommited for brevity
        
         bool RequestIsFromSwaggerUI() => Request.Path.StartsWithSegments("/swagger");
 }
```
I was wondering if I could extract this logic to be declared in Program.cs as it this not seem to be something my custom handler should be concerned about, imho.
