### ISSUE TITLE
How can I get the Config in my BaseEndpoint's Configure

### ISSUE THREAD

**Issue by zhixXiang** [dj-nitehawk/FastEndpoints#87]
I have a BaseEndpoint class that every endpoint inherit it.
But I need access config settings(appsettings.json) in the Configure area, so I use Config Property in endpoint, but it always null.
How can I get the Config in my BaseEndpoint's Configure?

**Comment by nefarius** [comment]
If you'd do dependency injection via constructor your configuration should be available, no?

**Comment by zhixXiang** [comment]
> If you'd do dependency injection via constructor your configuration should be available, no?

If I do contructor injection that every child endpoint need to write contructor base function.
So I tried the property injection but it cannot work

**Comment by nefarius** [comment]
Ah, fair point! **But**, just as a test to rule out things, does constructor injection work?

**Comment by dj-nitehawk** [comment]
accessing `IConfiguration` from within the endpoint `Configure()` method works now starting `v4.1.0-beta4`. 
normally it's not possible to resolve DI services before the container is built. when the endpoint `Configure()` method is called, the container is still not built and services are being registered. that is why we need the alternative approach of passing down the `IConfiguration/ConfigurationManager` to `AddFastEndpoints(...)` below:
```csharp
global using FastEndpoints;
using FastEndpoints.Security;

var builder = WebApplication.CreateBuilder();
builder.Services.AddFastEndpoints(config: builder.Configuration); //need to pass down the ConfigurationManager
builder.Services.AddAuthenticationJWTBearer("xxxxxxxxxxxxxxxx");

var app = builder.Build();
app.UseAuthorization();
app.UseFastEndpoints();
app.Run();

public abstract class EndpointBase<TRequest, TResponse> : Endpoint<TRequest, TResponse>
    where TRequest : notnull, new()
    where TResponse : notnull, new()
{
    public override void Configure()
    {
        var roles = Config?.GetSection("Settings:Roles")?.Value!; //accessing Config property works now
        Roles(roles);
    }
}

public class Test : EndpointBase<EmptyRequest, object>
{
    public override void Configure()
    {
        base.Configure();
        Get("test-endpoint");
    }

    public override async Task HandleAsync(EmptyRequest req, CancellationToken ct)
    {
        await SendAsync("all good!");
    }
}
```

**Comment by zhixXiang** [comment]
@dj-nitehawk Thank you! It works for me.

**Comment by GFoley83** [comment]
You can also use the HttpContext to retrieve a required service, which mean that you wouldn't need to avoid the need for derived Endpoint classes to have to add it to the constructor:

```csharp
public class EndpointBase<TRequest, TResponse> : Endpoint<TRequest, TResponse> where TRequest : notnull where TResponse : notnull
{
    private ISender? _mediator;

    protected ISender Mediator => _mediator ??= HttpContext.RequestServices.GetService<ISender>()!;

    protected EndpointBase() { }

    public override void Configure() { . . . }
}

public class Create() : EndpointBase<CreateTodoRequest, CreateTodoResponse>
{
    public override void Configure()
    {
        base.Configure();
        Post("api/todos");
    }

    public override async Task HandleAsync(CreateTodoCommand request, CancellationToken ct)
    {
        Response = await Mediator.Send(request, ct); // Access property in derived class without needing to update base 
    }
}
```
This is pretty much the only time I would condone resolving a service this way.
