### ISSUE TITLE
Adding support for FluentValidations and swagger schema.

### ISSUE THREAD

**Issue by NeskireDK** [dj-nitehawk/FastEndpoints#89]
I wish to register FluentValidation rules, so that they show up in swagger schema. 
Given the sample code below: 
```
public class Validator : AbstractValidator<ClosureScheduleCommand> 
{
    public Validator()
    {
        RuleFor(x => x.Warehouse).NotEmpty();
    }
}
```
We should be able to correctly mark the property as required. 
Example of the wanted schema presentation in Swagger
![image](https://user-images.githubusercontent.com/10115530/162982388-15350c5f-6e35-4786-a9a8-ece1bd82cfd2.png)
_The required field is marked by a red asterix. In this example i relied on the attribute [JsonRequired]_

Similar implementations in MVC aspnetcore 3.1: 
- https://github.com/micro-elements/MicroElements.Swashbuckle.FluentValidation.WebApi
- https://github.com/zymlabs/nswag-fluentvalidation

**Comment by NeskireDK** [comment]
Comments regarding this issue on Discord: 
**Dĵ ΝιΓΞΗΛψΚ**: _yeah looks like we're gonna have to write a nswag schema processor that's aware of fluentvalidations. could you pls maybe create a feature request on github for this? someone may pick up the task as i don't have the capacity to look into it myself for the next couple of weeks._ 

Full dump
![image](https://user-images.githubusercontent.com/10115530/162984359-5804feb4-1b82-4fd3-9da2-de9d76873b8b.png)

**Comment by NeskireDK** [comment]
Related to https://github.com/dj-nitehawk/FastEndpoints/pull/116/commits 
Schema is correctly created, if not using inheritance.

However the below does not work for my setup. (Might be related to startup config, still tracking it down)
CarRequest : BaseRequest{}

BaseRequest
{
 Public Guid Identifier {...}
}

**Comment by dj-nitehawk** [comment]
@NeskireDK are you using v4.2 released today?

**Comment by dj-nitehawk** [comment]
@wjax will you be able to look in to this?

**Comment by NeskireDK** [comment]
The primary issue seems to be, that all fluentvalidation rules gets ignored as soon as inheritance is used. With inheritance the 4 last properties have no schema rules: Required, Length etc. But without inheritance, simply copy paste, they do. Exactly as described by @wjac on discord: https://discord.com/channels/933662816458645504/955771546654359553/974938790546255882s

In conclusion the [PR 116](https://github.com/dj-nitehawk/FastEndpoints/pull/116/commits/3fddaff961e8da6b2c50cb08f2b76cf6bb6c8abf), that added the below hasn't solved the issue with base class inheritance. 
```csharp
 // Add properties from base class
ApplyRulesToSchema(context, schema.InheritedSchema, validator);
```

There's a secondary issue. If we look at the example with Inheritance, the property 'Identifier' becomes required, even though it is clearly not, as it defaults to new guid. Furthermore, there are no fluentvalidation rules or attributes assigned to 'Identifier'

### Example here with inheritance.
![image](https://user-images.githubusercontent.com/10115530/169263077-6e29613e-dea0-4238-a7e8-e98159b14ae2.png)

```csharp
public class SaveRule : EndpointWithRepository<HomeStationRuleRequest, HomeStationRuleResponse, IHomeStationRuleRepository>
{
    public override void Configure()
    {
        Put("Rules/HomeStation");
        base.Configure();
        Summary(summary => summary.Description = $"Saves a new or updates already existing 'Home Station Rule'");
    }

    public override async Task HandleAsync(HomeStationRuleRequest req, CancellationToken ct)
    {
        var result = await Repository.SaveAsync(Mapper.Map<HomeStationRule>(req));
        await SendAsync(Mapper.Map<HomeStationRuleResponse>(result), cancellation: ct);
    }
}
    
public class HomeStationRuleRequest : BaseIdentifier
{
    public string HomeStation { get; set; }
    public Guid ClosingDayIdentifier { get; set; }
    public Guid FlightOperatorId { get; set; }
    public DateTime ValidFrom { get; set; }
}

public class BaseIdentifier
{
    public Guid? Identifier { get; set; } = Guid.NewGuid();
}

public class RequestValidator : Validator<HomeStationRuleRequest>
{
    public RequestValidator()
    {
        RuleFor(x => x.HomeStation).HomeStationValidation();
        RuleFor(x => x.ClosingDayIdentifier).NotEmpty().NotNull();
        RuleFor(x => x.FlightOperatorId).NotEmpty();
        RuleFor(x => x.ValidFrom).NotEmpty().NotNull();
    }
}
```

### Example without inheritance.
![image](https://user-images.githubusercontent.com/10115530/169262491-399d61eb-d9f8-47e3-a4d5-8492a38f189d.png)
```csharp
public class SaveRule : EndpointWithRepository<HomeStationRuleRequest, HomeStationRuleResponse, IHomeStationRuleRepository>
{
    public override void Configure()
    {
        Put("Rules/HomeStationNoInheritance");
        base.Configure();
        Summary(summary => summary.Description = $"Saves a new or updates already existing 'Home Station Rule'");
    }

    public override async Task HandleAsync(HomeStationRuleRequest req, CancellationToken ct)
    {
        var result = await Repository.SaveAsync(Mapper.Map<HomeStationRule>(req));
        await SendAsync(Mapper.Map<HomeStationRuleResponse>(result), cancellation: ct);
    }
}
    
public class HomeStationRuleRequest 
{
    public Guid? Identifier { get; set; } = Guid.NewGuid();

    public string HomeStation { get; set; }
    public Guid ClosingDayIdentifier { get; set; }
    public Guid FlightOperatorId { get; set; }
    public DateTime ValidFrom { get; set; }
}


public class RequestValidator : Validator<HomeStationRuleRequest>
{
    public RequestValidator()
    {
        RuleFor(x => x.HomeStation).HomeStationValidation();
        RuleFor(x => x.ClosingDayIdentifier).NotEmpty().NotNull();
        RuleFor(x => x.FlightOperatorId).NotEmpty().NotNull();
        RuleFor(x => x.ValidFrom).NotEmpty().NotNull();
    }
}
```

**Comment by wjax** [comment]
I will look at it. 
It worked in my examples, but you know... ;)

Can you provide a repo with an "non-working" example?

**Comment by NeskireDK** [comment]
> I will look at it. It worked in my examples, but you know... ;)
> 
> Can you provide a repo with an "non-working" example?

Yes, its the least I can do. https://github.com/NeskireDK/FastEndpointsPlayground

**Comment by wjax** [comment]
Ok, After some investigation, I have some thought to throw to you all.

Inheritance is now working in my branch, however there are some things to discuss if we want to allow first level swagger validation support.

### Inheritance. Validation at Request type level
```csharp
public class Request : BaseIdentifier
{
    public Guid? NullableIdentifier { get; set; }
    public string? Message { get; set; }
}

public class BaseIdentifier
{
    public Guid Identifier { get; set; } = Guid.NewGuid();
}

public class RequestValidator : Validator<Request>
{
    public RequestValidator()
    {
        RuleFor(x => x.Identifier).NotEmpty();
        RuleFor(x => x.NullableIdentifier).NotEmpty();
        RuleFor(x => x.Message).Length(3, 100);
    }
}
```
This is working.

### Inheritance. Validation at any level
```csharp
public class Request : BaseIdentifier
{
    public Guid? NullableIdentifier { get; set; }
    public string? Message { get; set; }
}

public class BaseIdentifier
{
    public Guid Identifier { get; set; } = Guid.NewGuid();
    public string baseMessage { get; set; }
}

public class RequestValidator : Validator<Request>
{
    public RequestValidator()
    {
        RuleFor(x => x.Identifier).NotEmpty();
        RuleFor(x => x.NullableIdentifier).NotEmpty();
        RuleFor(x => x.Message).Length(3, 100);
    }
}

public class BaseIdentifierValidator : Validator<BaseIdentifier>
{
    public BaseIdentifierValidator()
    {
        RuleFor(x => x.baseMessage).Length(10, 100);
    }
}
```
In this case we take into account the validators of the parents so the child object (the request) has also inherited the validators from the parents.
It seems right to me to support this case.

###Composition
What about composition. Currently it is not supported. Imagine the following:
```csharp
public class Request
{
    public Guid? NullableIdentifier { get; set; }
    public string? Message { get; set; }
    public BaseIdentifier baseid { get; set; }
}

public class BaseIdentifier
{
    public Guid Identifier { get; set; } = Guid.NewGuid();
    public string messageBase { get; set; } 
}

public class RequestValidator : Validator<Request>
{
    public RequestValidator()
    {
        RuleFor(x => x.NullableIdentifier).NotEmpty();
        RuleFor(x => x.Message).Length(3, 100);
        RuleFor(x => x.baseid.Identifier).NotEmpty(); // This does not work currently
    }
}

public class BaseIdentifierValidator : Validator<BaseIdentifier>
{
    public BaseIdentifierValidator()
    {
        RuleFor(x => x.messageBase).Length(10, 100);
    }
}
```
Swagger should provide validation for composition.
BaseIdentifierValidator is ingnored and not incorporated into swagger data.
But even worse, a Rule with a field from an "internal" object neither.

So what cases should be supported.
All of them seems good to me

**Comment by dj-nitehawk** [comment]
first two cases I'd say yes.
third case/ composition I'd say nah. 
I would certainly not write validators like that personally. 
let's see what others have to say.

**Comment by wjax** [comment]
Talking about the composition thing,

How would I validate this:
```csharp
public class Request
{
    public Guid? NullableIdentifier { get; set; }
    public string? Message { get; set; }
    public SomeEntity[] entities { get; set; }
}

public class SomeEntity
{
    public Guid Identifier { get; set; } = Guid.NewGuid();
    public string messageBase { get; set; } 
}

public class RequestValidator : Validator<Request>
{
    public RequestValidator()
    {
        RuleFor(x => x.NullableIdentifier).NotEmpty();
        RuleFor(x => x.Message).Length(3, 100);
    }
}

public class BaseIdentifierValidator : Validator<SomeEntity>
{
    public BaseIdentifierValidator()
    {
        RuleFor(x => x.messageBase).Length(10, 100);
    }
}
```
Is this case a non-sense?

**Comment by dj-nitehawk** [comment]
"set validator for each entity" i believe: https://docs.fluentvalidation.net/en/latest/collections.html?#collections-of-complex-types

**Comment by wjax** [comment]
Ok, 

I'll see what I can do. Will pull request soon!

**Comment by dj-nitehawk** [comment]
@NeskireDK can you try `v4.3.0-beta2` and give us some feedback on this?

**Comment by NeskireDK** [comment]
Sure. The original issue has been resolved beautifully. Thanks a lot, this is 95% of all cases now correctly working in my private repository. 
I've updated my repository to reflect as such. In addition i've added 2 more cases, that unfortunately is not working / supported either. 

That being 
- Validation specifying a validator for child: `RuleFor(x => x.HeadQuarters).SetValidator(new AddressValidator());`
- Inheritance Validators: `RuleFor(x => x.Contact).SetInheritanceValidator(v => v.Add<Type>(new ..);`
_As described [here](https://docs.fluentvalidation.net/en/latest/inheritance.html)_

The validations are correctly run and submission gets stopped with status 400, including validation message.
However the swagger schema once again doesn't show up for child elements this time. 

Source code: https://github.com/NeskireDK/FastEndpointsPlayground
Remaining failing schema endpoints: 
- SaveWithChildValidator 
- SaveWithInheritanceValidator

**Comment by NeskireDK** [comment]
> After some discussion with @dj-nitehawk we will keep the current support for a single validator against the request type of the endpoint. We will not make complex things injecting base validators automatically that could break the surface api or make things too complex.
> 
> Of course the requestDto can use inheritance and it will play nice with both the validator and the swagger support.
> 
> So, in case anyone needs to reuse a validator from a base type, he/she can use inheritance in the validator like this:
> 
> ```cs
> public class Request : BaseIdentifier
> {
>     public string? NullableIdentifier { get; set; }
>     public string? Message { get; set; }
> }
> 
> public class BaseIdentifier
> {
>     public string Identifier { get; set; }
>     public string baseMessage { get; set; }
> }
> 
> public class RequestValidator : BaseIdentifierValidator<Request>
> {
>     public RequestValidator()
>     {
>         RuleFor(x => x.Identifier).NotEmpty();
>         RuleFor(x => x.NullableIdentifier).NotEmpty();
>         RuleFor(x => x.Message).Length(3, 100);
>     }
> }
> 
> public class BaseIdentifierValidator<TDto> : Validator<TDto> where TDto : BaseIdentifier
> {
>     public BaseIdentifierValidator()
>     {
>         RuleFor(x => x.baseMessage).Length(10, 100);
>     }
> }
> ```

I quite agree with this approach. However, see post [above](https://github.com/dj-nitehawk/FastEndpoints/issues/89#issuecomment-1133553810) which attempts to do explicit child inheritance, and schema not showing the validation.

**Comment by wjax** [comment]
Opened a new issue to track these missing pieces
https://github.com/dj-nitehawk/FastEndpoints/issues/127
