### ISSUE TITLE
Is there a way to omit an endpoint from the generated swagger?

### ISSUE THREAD

**Issue by pvaillant** [dj-nitehawk/FastEndpoints#90]
I have several endpoints and I have enabled swagger generation. All the endpoint appear but I would like to omit one or two since they are internal endpoints and I'd like to use the generated swagger as a basis for public clients. I've looked through the docs at https://fast-endpoints.com/wiki/Swagger-Support.html and Endpoint.Setup.cs but I didn't see anything. I also tried to apply [ApiExplorerSettings(IgnoreApi = true)] to the Endpoint class but that didn't work. Is there a way to accomplish this?

**Comment by dj-nitehawk** [comment]
yes, by doing this:
```csharp
public override void Configure()
{
    Get("internal-endpoint");
    Description(x => x.ExcludeFromDescription());
}
```

**Comment by pvaillant** [comment]
That is exactly what I was looking for! Thank you very much!
