### ISSUE TITLE
Model binding revamp idea: switching to a more traditional approach

### ISSUE THREAD

**Issue by DCichosz** [dj-nitehawk/FastEndpoints#92]
```csharp
public class Request
{
    // binds from route
    public int Id { get; set; }

    // binds from header
    [FromHeader]
    public int UserId { get; set; }

    // bind from body
    public MeetingBoardInput MeetingBoard { get; set; }
}
```

Swagger will generate body schema like this: 
`{ MeetingBoard: {...} }`

There is always parent object above desired object which is actually your model for the body which is not consistent or common pattern.

If you are able to put all of the needed properties in Request model and actually you can explicitly tell from where the property should be bound it should have more organized way of handling the binding. I would implement explicit markers instead of the order
so then you can tell in the model from where the values should come (FromBody, FromQuery, FromRoute, FromHeader)
and then if it's possible I would take the object type that is marked to take from body (FromBody attribute) and use it as endpoint request input dto in swagger body schema. 
This way we can organize request dto so we can provide blocks based on binding source and swagger will only generate the schema for request body.

**Comment by dj-nitehawk** [comment]
if someone is willing to send in a PR for this, we can ship it as a major breaking change in `v5.0` as this would be a complete revamp of the model binding logic.

pls do note that the PR will only be accepted if there's no performance degradation compared to the current approach.

PR should also update the `NSwag schema processor` and fix up existing integration tests as well as provide full test coverage of the new code.

this may be a difficult task for any one individual to achieve. if people are interested in contributing, we can discuss it further in the discord channel and come up with a plan.

**Comment by dj-nitehawk** [comment]
`v4.4.0-beta4` now has a `[FromBody]` property which can be used to mark a property on the dto which should be bound from the incoming request json body. atm, binding works but swagger integration still needs to be done.

**Comment by dj-nitehawk** [comment]
swagger integration for `[FromBody]` is done with `v4.4.0-beta6`
i'll close this issue for now since the new change get's the job done.
