### ISSUE TITLE
Importance of order of generic type params when inheriting Endpoint<TRequest, TResponse> should be documented or changed

### ISSUE THREAD

**Issue by JustMaier** [dj-nitehawk/FastEndpoints#94]
While trying to create an abstraction on top of FastEndpoints, we ran into an issue where the Validator wasn't running as expected. The code that caused the issue looked a little like this:

```csharp
public class AddCourseEndpoint : AddEntityEndpoint<Course, AddCourseRequest, AddCourseReponse> {}
public class AddEntityEndpoint<TEntity, TRequest, TResponse> : Endpoint<TRequest, TResponse> {}
public class AddCourseRequestValidator : Validator<TRequest> {}
```

After much digging into how FastEndpoints picks the validator for an endpoint, we found this line in [`EndpointData.cs`](https://github.com/dj-nitehawk/FastEndpoints/blob/5732f68120dd1148e034f5401290b1d9e9698045/Src/Library/Extensions/EndpointData.cs#L87) that picks the request type by simply taking the first generic type param of the endpoint class. Since our abstraction put `TEntity` as the first generic type param, the endpoint data was looking for a validator of type `Course` rather than `AddCourseRequest`. 

It seems like one of two things should be done:
1. The required order of the generic types should be documented, perhaps on a page about Endpoint inheritance and on the API Reference page of `Endpoint<TRequest, TResponse>` _OR_
2. The offending line mentioned above should be adjusted so that it can pick the correct type parameter independent of order.

**Comment by JustMaier** [comment]
@dj-nitehawk I've just submitted a PR that should be able to more effectively find the correct type param.

**Comment by dj-nitehawk** [comment]
thanks again for the PR. good stuff...
`v4.1.0-beta5` released with this...
