### ISSUE TITLE
Can we replace "CQRS" pattern using MediatR with FastEndPoints ? 

### ISSUE THREAD

**Issue by MeAnupSarkar** [dj-nitehawk/FastEndpoints#96]
I learnt that MediatR library causes performance degradation and more memory consumption. Is it good idea to replaced by FastEndPoints ? what is your thought  regarding this?

**Comment by dj-nitehawk** [comment]
sure you can. fastendpoints has handler methods, pub/sub event bus, and pre/post-processors as an alternative to mediatr pipelines.

me personally, see no real benefit in seperating reads/writes as done with CQRS, so i just stick to tightly coupled vertical slices as done here: https://dev.to/djnitehawk/building-rest-apis-in-net-6-the-easy-way-3h0d

**Comment by MeAnupSarkar** [comment]
This is what I was looking for.
Thanks
