### ISSUE TITLE
Route parameter property type not correctly set with swagger

### ISSUE THREAD

**Issue by sandervn** [dj-nitehawk/FastEndpoints#99]
When using a route parameter in the URL, the type of the property is not correctly set in swagger.
For example: 
```
 Get("/test/{ProjectId}");
```
with the following request:
```
public class Request
{
    public int ProjectId { get; set; }
}
```
The swagger should set the type of the ProjectId to int but currently it's set to string.
![image](https://user-images.githubusercontent.com/44084906/165950442-8f41b7ca-17e6-44d0-b942-d0de2c35ee05.png)

**Comment by dj-nitehawk** [comment]
this is a known limitation which needs to be implemented [here](https://github.com/dj-nitehawk/FastEndpoints/blob/main/Src/Swagger/OperationProcessor.cs#L186)

if someone's upto taking this small task on, pls submit a PR 🙏

**Comment by meysamhadeli** [comment]
Hi. I did this issue #104.

**Comment by dj-nitehawk** [comment]
@meysamhadeli highly appreciate the PR.
will be released today in `v4.2.0-beta2`

**Comment by sandervn** [comment]
Thanks for fixing this 🥳

**Comment by Kingside88** [comment]
Hi Thanks for supporting.
I still have the same problem. The route parameter is not showing up in swagger. 
Using FastEndpoints 5.24.0

**Comment by dj-nitehawk** [comment]
@Kingside88 pls open a new issue with repro code so we can help you. afaik everything works as intended.
